### ISSUE TITLE
add Layer to group

### ISSUE THREAD

**Issue by bufferclip** [nextgis/quickmapservices#105]
I use QuickMapServices mostly for basemaps. I put all my basemaps in a group:

![qms](https://cloud.githubusercontent.com/assets/15704517/18036433/53431a6c-6d6a-11e6-9d4f-83edb9a38371.png)

Then I set the group to be mutually exlusive:

![menu](https://cloud.githubusercontent.com/assets/15704517/18036443/8ab66198-6d6a-11e6-97a5-b3fe4b1cf490.png)

I would like to add new QuickMapService Layers directly to my basemap-group. 
However, when I activate the group and add a new basemap from QuickMapServices, then new basemap is placed outside of the group.

![outside](https://cloud.githubusercontent.com/assets/15704517/18036455/f6921f9c-6d6a-11e6-9f2e-b9f4dfa9caa0.png)

So my suggested feature would be:

**when a group is activated a new QuickMapServices Layer should be placed inside the group and not outside**

**Comment by alisovenko** [comment]
Done

**Comment by alisovenko** [comment]
Done
