### ISSUE TITLE
Grayscale option doesn't get saved in the project

### ISSUE THREAD

**Issue by nextstopsun** [nextgis/quickmapservices#106]
When saving project with a Grayscale option turned on and then reopening it, the layer is displayed in color. The option doesn't get saved in the project, which is uncool. QGIS 2.16 on OSX.

**Comment by simgislab** [comment]
version of QMS?
this was fixed here: https://github.com/nextgis/quickmapservices/issues/91

**Comment by nextstopsun** [comment]
Version 0.17.4. Tested on QGIS 2.16.0, OS X.

**Comment by simgislab** [comment]
you are two versions behind current
http://plugins.qgis.org/plugins/quick_map_services/
