### ISSUE TITLE
Rely on QGIS' native TMS support when possible

### ISSUE THREAD

**Issue by nirvn** [nextgis/quickmapservices#110]
QGIS now supports TMS natively (thanks to Martin's amazing work here); it'd be good for QuickMapServices to serve map layers using that method instead of a custom plugin-level implementation. This would unlock:
- rotation support
- progressive rendering
- support for loading those layer with users that don't have quickmapservice installed and/or activated on their machine
- and more... :smile:

**Comment by simgislab** [comment]
a little more here: http://www.lutraconsulting.co.uk/blog/2016/10/26/qgis-xyz-tile-wmts-preview/

>support for loading those layer with users that don't have quickmapservice installed and/or activated on their machine
I didn't quite get this. We're talking about QMS here, right?

**Comment by nirvn** [comment]
Yes. I mean to suggest that QMS should rely on QGIS' native XYZ support instead of QMS'implementation. In essence QMS keep the same great UI (and keep contributor pack) to serve XYZ basemaps, which would be loaded as native XYZ layers.

**Comment by yellow-sky** [comment]
At the moment only URL can be specified  for native XYZ implementation. There are not enough options: YTopOrigin, ZMin, Zmax, CRSID. QMS has a lot of service definitions that require these options.

We've planned for a long time to prepare a better TMS implementation through GDAL, but failed to find resources for it yet.

**Comment by wonder-sk** [comment]
Actually zMin, zMax options are supported, they are just not exposed in the GUI.

Inverted Y axis and CRS different from web mercator are currently not supported in XYZ implementation, but from a quick look these options are used only in 6 services out of ~100

**Comment by simgislab** [comment]
few other concerns:

- domains
- custom tiling parameters added with https://github.com/nextgis/quickmapservices/pull/75
