### ISSUE TITLE
QuickMapServices (QGIS extension) - OpenTopoMap cannot be loaded

### ISSUE THREAD

**Issue by Salomo1** [nextgis/quickmapservices#111]
Dear NextGIS team, you have written the tool "QuickMapServices" as an extension to QGIS - to load freely available topographic maps. One can load e.g. OpenStreetMap without problems. But it is impossible to load OpenTopoMap, although it appears in the extensions menu, and although the the layer name appears in the layer window on the left, in addition a message appears: "0 files downloaded, 16 cashes hit". But the map window remains empty. Could you friendly eliminate the error? - Thank you very much!

**Comment by simgislab** [comment]
fixed with https://github.com/nextgis/quickmapservices_contrib/commit/b5dedbd5eef1b0ab15b5f852d005946f63d76f0f
