### ISSUE TITLE
OpenTopoMap layer issue

### ISSUE THREAD

**Issue by NicolasDumoulin** [nextgis/quickmapservices#112]
Hi,

In the past, I had no problem, but since some weeks, I can't use anymore the layer OpenTopoMap with this plugin.
QGis 2.8.6-Wien under ubuntu 16.04.1
Others layers, like mapnik default, TF Outdoors are fine. But now, opentopomap doesn't bring any coherent tile. Instead, it displays other tiles (from mapnik) with some weird effects.
I see nothing when launching qgis from a terminal or in the "messages" toolbox.

How can I fix that?
Is there a way to reset the cache for example, or investigate the problem?

Thanks

**Comment by simgislab** [comment]
Hi, check this first: https://github.com/nextgis/quickmapservices/issues/111#issuecomment-259178234

Let me know if problems goes away.

**Comment by NicolasDumoulin** [comment]
So nice, it fixes my issue!

Thanks a lot Maxim!
