### ISSUE TITLE
TMS with non-standard tiling structure

### ISSUE THREAD

**Issue by simgislab** [nextgis/quickmapservices#118]
It seems like QMS fails to process TMS where tile scheme is different from basic z/x/y

Example:

http://m1.mapserver.mapy.cz/ophoto-m/${z}-${x}-${y}

https://m1.mapserver.mapy.cz/ophoto-m/9-271-172

https://qms.nextgis.com/geoservices/694/

Also:

https://qms.nextgis.com/geoservices/681/

More (slightly different structure):

https://qms.nextgis.com/geoservices/680/

**Comment by alisovenko** [comment]
Should use {z}-{x}-{y} instead of ${z}-${x}-${y}.
Problem with https://qms.nextgis.com/geoservices/680/ fixed in qms 0.18.2 - Use rediration url, if tms service return 301 http status start
