### ISSUE TITLE
Слой "osm-mostrans moscow trolleybus (TMS)" не добавляется в QGIS

### ISSUE THREAD

**Issue by trolleway** [nextgis/quickmapservices#119]
# Шаги для воспроизведения

1. Открыть QGIS
2. В панели QMS ввести запрос "mostrans", и попытаться добавить слои
![image](https://cloud.githubusercontent.com/assets/4630662/21962469/e8951e90-db37-11e6-948d-a0fabc5538c7.png)

# Ожидаемое поведение

Оба слоя добавляются на карту

# Фактическое поведение

Слой bus добавляется, а слой trolleybus - нет.  В веб-интерфейсе qms они оба в лифлете показываются правильно, url тоже не отличается.
https://qms.nextgis.com/geoservices/656/
https://qms.nextgis.com/geoservices/647/

**Comment by trolleway** [comment]
На другом компьютере с новым ngqgis под Ubuntu - то же самое.

**Comment by simgislab** [comment]
оба работают, если нет - переоткрывай
