### ISSUE TITLE
coordinatecaptureplugin.dll broken?

### ISSUE THREAD

**Issue by zlqs1985** [nextgis/quickmapservices#120]
I download the zip file and upzip it to the directory
`C:\Program Files\QGIS 2.18\apps\qgis\python\plugins`
My QGIS version is 2.18.3
and I also enable the plugin in the plugin manager
However the manager show me the error message like 

```
Coordinate Capture

Capture mouse coordinates in different CRS




Category: Vector 

Installed version: Version 0.1 (in C:/PROGRA~1/QGIS2~1.18/apps/qgis/plugins/coordinatecaptureplugin.dll)
```

**Comment by simgislab** [comment]
I don't see how this is realted to QMS plugin
