### ISSUE TITLE
Settings dialogue broken in 0.18.3

### ISSUE THREAD

**Issue by andywicht** [nextgis/quickmapservices#125]
Since yesterdays (Feb. 26, 2017, 2:03 a.m.) update to 0.18.3 the settings dialogue is broken resulting in following python error:
```
NameError: global name 'QHeaderView' is not defined 
Traceback (most recent call last):
  File "C:/Users/aw/.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 299, in show_settings_dialog
    settings_dlg = SettingsDialog()
  File "C:/Users/aw/.qgis2/python/plugins\quick_map_services\settings_dialog.py", line 52, in __init__
    self.treeViewForDS.header().setResizeMode(DSManagerModel.COLUMN_GROUP_DS, QHeaderView.Stretch)
NameError: global name 'QHeaderView' is not defined
```
I tested on different machines (Win7) with QGIS 2.18.3 and 2.18.4. 
The installation and layer display works, but the settings do not.
Version 0.18.1 was running just fine!

**Comment by simgislab** [comment]
thanks for spotting it so quickly!

**Comment by andywicht** [comment]
spottet it by pure coincidence! happy to help
