### ISSUE TITLE
TMS support for  sardegnageoportale.it TMS ...

### ISSUE THREAD

**Issue by jdatalog** [nextgis/quickmapservices#129]
Hi all,
I tried without success to add the support of following TMS services : [ Sardegna Geoportale TMS service](http://www.sardegnageoportale.it/index.php?xsl=1594&s=40&v=9&c=9875&na=1&n=100)

For example for TMS Stradario I create the folowing metadata.ini :
[general]
id = Sardegna_Stradateto
type = TMS
epsg_crs_id = 3003

[ui]
group = Tophe
alias = Stradateto
icon = sardegne.png

[license]
name = Public
link = 
copyright_text = 
copyright_link = 
terms_of_use = 

[tms]
url = http://webgis.regione.sardegna.it/tms/stradario/stradario_EPSG3003/{z}/{x}/{y}.png
zmin = 0
zmax = 14
y_origin_top = 0

Info for this TMS service are here : [ stradario TMS service](http://www.sardegnageoportale.it/index.php?xsl=1598&s=203498&v=2&c=9875&t=1) 

Any help will be greatly appreciated :-)

  Christophe

**Comment by simgislab** [comment]
Hi, 
judging from http://webgis.regione.sardegna.it/tms//stradario_EPSG3003/2/2/0.png

this is non standard tiling scheme.

We do support non-standard schemes now, but I not sure that what you need will fit in current implementation

https://github.com/nextgis/quickmapservices_contrib/pull/24/commits/7984e571cb6a9f502549c43c51099a0ba56fdad3
