### ISSUE TITLE
Broken tile layer dialog keeps popping up

### ISSUE THREAD

**Issue by culebron** [nextgis/quickmapservices#131]
If this dialog opens, pressing `Escape` makes it appear again, same when pressing `Abort`. Only "Ignore" makes it disappear.

![selection_001](https://cloud.githubusercontent.com/assets/119675/24609464/9c714596-1883-11e7-91be-08421cd0306e.jpg)

**Comment by simgislab** [comment]
This seems unrelated to QMS, general QGIS SSL behaviour.
