### ISSUE TITLE
QGis crashed after handling queued tiledownloads after connection failure on mobile connection

### ISSUE THREAD

**Issue by klmi** [nextgis/quickmapservices#134]
Hello together,

when using QGis on mobile connections  sometimes connection failes.
During this time the plugin caches the failed download request of tiles.
When connection is reestablished the queue is processed parallel to new requests.
Somehow when the number if queued requests increeses (e.g. >1000 requests) the plugin, and so Qgis, crashes.
Also closing the warning messaged (again > 1000 entries) on top of the displayed map leads to a crash of qgis.

Please find the error log attached:
[qgis-20170504-131536-6968-5764-cd9d645.zip](https://github.com/nextgis/quickmapservices/files/978294/qgis-20170504-131536-6968-5764-cd9d645.zip)

If I need to provide further information don't hesitate to contact me :-D

with kind regards,

Michael

**Comment by simgislab** [comment]
please reopen if new native time provider/qgis didn't fix it
