### ISSUE TITLE
WMS fails after update to 0.18.6

### ISSUE THREAD

**Issue by PedroVenancio** [nextgis/quickmapservices#135]
Hi @alisovenko 

Some time ago I've added some Portuguese web map services [0] that stopped to work after the update of QuickMapServices to version 0.18.6. 

I saw that the update was based on this commit [1] to fix custom wms parameters.

How should I update the services, to be compliant with the fix?

Thanks!

Best regards,
Pedro

[0] https://github.com/nextgis/quickmapservices_contrib/commit/ec36357671f99c16c87c7ca078074a7b5b9a9d05 
[1] https://github.com/nextgis/quickmapservices/commit/b65c5028c05765b349c0026d4af0092150dfea94

**Comment by alisovenko** [comment]
Hi @PedroVenancio!

Yes it is a bug

But you can fix it by remove "&layers=Concelhos-2016&styles=" from parameters string here:
https://github.com/nextgis/quickmapservices_contrib/blob/master/data_sources/caop_concelhos/metadata.ini#L19
You have already pointed out the layers:
https://github.com/nextgis/quickmapservices_contrib/blob/master/data_sources/caop_concelhos/metadata.ini#L20

Also you can configure your services here https://qms.nextgis.com/. 
Support quickmapservices_contrib will be deprecated.

Best regards,
Alexander

**Comment by PedroVenancio** [comment]
Thak you very much for the fix @alisovenko !

Best regards,
Pedro
