### ISSUE TITLE
QuickMapServices: Failed to download all 18 files. - GLAD Alert forest loss 2017

### ISSUE THREAD

**Issue by sleepiejew** [nextgis/quickmapservices#138]
This message pops up for several plugins.This is just one example.
I am new to this plugin and I love it! (Fills some holes in openlayers issues)
But I'm not at all sure what is causing these issues, and if there's anything I am doing wrong

**I submitted a similar message to the service's author, through the QMS site. So if this is a servicer issue, I apologize for taking up space here.

2.14.5 LTR, Windows 10, 32-bit

Thanks! 
(PS this is my first Issue post on GitHub, so if I am not following proper decorum please let me know!)

**Comment by simgislab** [comment]
Hi, https://qms.nextgis.com/geoservices/1028/ tiles return 404. So this is definitely a provider issue, not QMS. We can't really fix it, but we're taking steps to hide such services, until they become operational again.

**Comment by sleepiejew** [comment]
Okay, this is what is suspected. That would be a great addition, hiding error services. Kudos on your work.
Thanks
