### ISSUE TITLE
QMS crashes QGIS 2.18.13 on Ubuntu 16.04 x64

### ISSUE THREAD

**Issue by geokimbo** [nextgis/quickmapservices#142]
After upgrading QGIS last week it automatically disables QMS because when ever it is enabled QGIS crashes. It's a great plugin and still works fine on another machine I have not upgraded so a fix would be  bonza!

**Comment by spencerbh** [comment]
Same issue here with Qgis 2.18.14 on Mint 18.1 (Ubuntu 16.04 x64)

**Comment by simgislab** [comment]
please reopen if problem persists on newer version of QMS plugin and QGIS
