### ISSUE TITLE
QMS for QGIS 3?

### ISSUE THREAD

**Issue by giohappy** [nextgis/quickmapservices#143]
Will QuickMapServices be available for QGIS 3?

**Comment by simgislab** [comment]
we don't know yet, pull-requests and support are welcome as usual

**Comment by giohappy** [comment]
Ok, just to know if there was some ongoing development. We will try to
contribute. It's one of the most appreciated plugins, it would be a big
loss not having it.

giovanni

Il 19 ott 2017 19:35, "Maxim Dubinin" <notifications@github.com> ha scritto:

**Comment by simgislab** [comment]
@drnextgis can you link up your branch, was it an attempt to upgrade to QGIS3?

**Comment by relima** [comment]
Any progress? This is a very important plugin to get to QGIS3.

**Comment by drnextgis** [comment]
@relima we have started crowd funding campaign for porting QMS to QGIS3: http://nextgis.com/qms-plugin-crowdfunding/

**Comment by HansRue** [comment]
+1

**Comment by alexey-gl** [comment]
Hello!
As well as I see crowdfunding campaign was successful, wasn't it?
Could you tell about the current progress please?

**Comment by alexey-gl** [comment]
Great, thank you!

**Comment by drnextgis** [comment]
[QuickMapServices for QGIS3](http://nextgis.com/blog/qms-qgis3/)
