### ISSUE TITLE
Couldn't load plugin teste due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by ThiagoTasSilva** [nextgis/quickmapservices#144]
Hey guys, i need help.

I am developing a project to create a plugin in QGIS, but I'm having this problem...

# Couldn't load plugin teste due to an error when calling its classFactory() method 

# ImportError: No module named resources 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/thiago_tassilva/.qgis2/python/plugins/teste/__init__.py", line 34, in classFactory
    from .teste import teste
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/thiago_tassilva/.qgis2/python/plugins/teste/teste.py", line 26, in 
    import resources
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named resources

Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] 
QGIS version: 2.18.13 Las Palmas, exported 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/thiago_tassilva/.qgis2/python
/Users/thiago_tassilva/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/scipy-override
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/2.1/Python/2.7/site-packages
/Library/Frameworks/cairo.framework/Versions/1/Python/2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Library/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Library/Python/2.7/site-packages/PIL
/Users/thiago_tassilva/.qgis2//python

**Comment by simgislab** [comment]
Not sure why you are posting this here. This seems unrelated to QMS plugin.
