### ISSUE TITLE
Ошибка get_geoservices при поиске по названию

### ISSUE THREAD

**Issue by trolleway** [nextgis/quickmapservices#145]
NextGIS QGIS 17.6.0 Windows
QMS  0.19.3
При вводе запроса в панель поиска выводится ошибка
![image](https://user-images.githubusercontent.com/4630662/32623745-3367069a-c598-11e7-9fde-0f6d153bb696.png)

**Comment by simgislab** [comment]
в 0.19.2 (последний релиз), QGIS 17.10.0 все норм
