### ISSUE TITLE
Adding API key for thunderforest cycle map

### ISSUE THREAD

**Issue by onlyMaps** [nextgis/quickmapservices#149]
![api](https://user-images.githubusercontent.com/6785759/34204292-5b4f85aa-e57e-11e7-9cec-f829af7dc58f.JPG)
Any chance to get information or help how to add my API key in your Plugin?

**Comment by simgislab** [comment]
the only way currently is include in service URL, but this is a bad solution if you'd like to make this service definition public

example: https://qms.nextgis.com/geoservices/1283/

**Comment by onlyMaps** [comment]
Thanks for your feedback on my question. I do not want to publish bicycle maps with the help of Qgis. I need to download cyclingruoutes and export them as TABor shape files - it seems that downloading to a osm file does not work unless a correct API key is specified.

Does my explanation make sense to you?

**Comment by simgislab** [comment]
based on what you said QMS is the wrong tool for your task
