### ISSUE TITLE
Greyscale Layer Propierties

### ISSUE THREAD

**Issue by Daviiidet** [nextgis/quickmapservices#150]
Hi guys,

First of all, congratulation for this tool is really really helpful.
But I have one problem. When I install or reinstall the plugin in the Qgis 2.18.14, is is possible to select the grey option to show the background. But, when I close Qgis and start again this option disappear and I need to reinstall the plugins.  Do you have idea why I have is?

Thanks a lot in advance,
David

**Comment by simgislab** [comment]
Hi, thanks for feedback

looks like https://github.com/nextgis/quickmapservices/issues/95 still persists

**Comment by simgislab** [comment]
we won't be fixing this as QGIS 3 has only native tile provider and this menu is not unavailble on 3
