### ISSUE TITLE
handle canvas rotation

### ISSUE THREAD

**Issue by gubuntu** [nextgis/quickmapservices#151]
QGIS 2.18

It would be great if QMS layers worked with a rotated canvas. 

Currently only part of the QMS layer renders and it is very warped at that. I have tried various QMS layers from different providers.

**Comment by simgislab** [comment]
There two renderers in QMS: QGIS native and QMS native, which one did you try? Which one doesn't work as expected?

Renderers can be switched in Settings/Tiles.

**Comment by gubuntu** [comment]
I didn't know about that setting (if it's ticked, which 'native renderer' will be used, QGIS or QMS?) but I've tried both now and neither work. I'm assuming it should switch without restarting QGIS.

**Comment by simgislab** [comment]
it shouldn't be restarted, but you should re-add the service

so you can have the same TMS added from the same source, but rendered with two different renderers

**Comment by gubuntu** [comment]
that does the trick, thanks! The images don't seem to be quite as crisp as when not rotated but it's the best solution so far.

**Comment by simgislab** [comment]
you still did tell us which renderer work and which didn't :) but I'm glad it worked anyway.

**Comment by gubuntu** [comment]
it worked with native renderer ticked. I assume that means QMS native renderer? I suggest adding QMS to the text so it's clear that it's the QMS native renderer.
