### ISSUE TITLE
changing CRS does not work (anymore)

### ISSUE THREAD

**Issue by Jan-v-W** [nextgis/quickmapservices#152]
when changing the CRS of the project (when zoomed in) to something else than EPSG:3857 qgis chrashes with segmentation fault.

QGisVersion 2.18.15 and 2.18.16
OS: 16.04
QMS Version: 0.19.3

I've tried it with several different services, always with the same result. (OSM Standard, MapSurfer OSM Roads, Google Satellite, a.o.)

More detail:
- I can load a service if project CRS is EPSG:3857. I can change the CRS, but when I zoom in QGis chrashes.
- If any the project CRS is anything other than EPSG:3857 and I switch on a QMS layer QGis chrashes

**Comment by simgislab** [comment]
are you using native provider or QMS internal? try switching back and forth under Settings/Tiles

**Comment by Jan-v-W** [comment]
Thanks that helped (I hope). I am now using the native renderer and it seems to be working.
