### ISSUE TITLE
Wrong QGIS version supported of native renderer 

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/quickmapservices#154]
In screenshot written ``2.8.8`` but should be ``2.18.8`` 
![2018-03-12 16 51 10](https://user-images.githubusercontent.com/1708122/37287530-0d5db4f6-2616-11e8-98d6-dceaabfeefd8.png)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/quickmapservices/commit/42cdff82374c73f581f10f23aa684a88ba833240
