### ISSUE TITLE
"Использовать встроенный рендер" должно быть включено по умолчанию

### ISSUE THREAD

**Issue by trolleway** [nextgis/quickmapservices#155]
![image](https://user-images.githubusercontent.com/4630662/37287516-0809ec2c-2616-11e8-8932-af2758241ba4.png)
А то количество нужных опций которые не включены по умолчанию, переходит разумное количество, половина тренинга по QGIS состоит из ходьбы по настройкам.

**Comment by simgislab** [comment]
так и есть
