### ISSUE TITLE
При вводе букв в поиск компьютер не должен зависать

### ISSUE THREAD

**Issue by trolleway** [nextgis/quickmapservices#157]
Шаги для воспроизведения:

В QGIS вводить в окно поиска "Московский". В процессе ввода буквы в поле будут появляться с задержкой, будет такой вид будто компьютер висит.

Желаемое поведение:
Если за последнюю секунду в поле введено больше двух символов, то запрос на поиск отправляется через 0,5 секунды после ввода последнего символа. 
Неужели в API которое формы рисует нет такого свойства?

**Comment by simgislab** [comment]
исправлено
