### ISSUE TITLE
Перезапись папок с настройками при обновлении плагина

### ISSUE THREAD

**Issue by SergeyRyzhkov** [nextgis/quickmapservices#16]
При обновлении плагина перезаписались папки quick_map_services\data_sources и quick_map_services\groups
что не очень хорошо, если сам настраиваю папки

**Comment by yellow-sky** [comment]
Да, это происходит потому что при переустановке плагинов QGIS полностью уничтожает старую версию.
В версии, в которой будет возможность добавлять собственные определения, эти файлы будут храниться в другом месте.

**Comment by SergeyRyzhkov** [comment]
Понял. Спасибо. 
А есть уже понимание в каком формате будет хранится описание источников данных, место хранения, мехнаизм обновления и т.д. ?

**Comment by yellow-sky** [comment]
Пока планировали оставить формат файлов прежним. Но храниться они будут не в директории плагина, а в директории локальных настроек QGIS.

**Comment by SergeyRyzhkov** [comment]
Понял. Кстати было бы удобно иметь несколько веток настроек, типа конфигураций. 
То есть имеем одинковые структуры папок и формат файлов с описанием, как сейчас, но в разных подпапках. И соотвественно быстрое переключение.
Например у меня есть 
...\python\plugins\quick_map_services\groups_main - основной профиль
...\python\plugins\quick_map_services\groups_cadastre - профиль для работы с кадастром
...\python\plugins\quick_map_services\groups_crimea - профиль про проекту Крыма
и т.д.
Понимаю что можно все в одну структуру засунуть, но все же удобнее иметь разные профили. У меня в профиле Крым около 60 !!! источников и разложены они соотвествующе...
Сейчас надо переименовыать папку и перезаходить, чтобы активизировать тот или иной профиль

**Comment by yellow-sky** [comment]
#19

**Comment by yellow-sky** [comment]
Close with 7de25bf939b946b590ae47d4982d3502eb56046a
