### ISSUE TITLE
QGIS 3.2 the plugin does not work

### ISSUE THREAD

**Issue by pigreco** [nextgis/quickmapservices#166]
![image](https://user-images.githubusercontent.com/7631137/41811902-812f6a20-7718-11e8-87fd-95222f88c861.png)

win 10 64 b
OSGeo4W

**Comment by gumimajom** [comment]
it does not work for me either
QGIS - 3.2.0-Bonn 'Bonn' (bc43194) @ Ubuntu 18.04 LTS

**Comment by luipir** [comment]
temporally just edit metadata.txt of the plugin and set qgisMaximumVersion version to 3.2 o 3.99 (now is set to 3.1)... I suppose they'll update the plugin soon. Btw it has been removed from plugin repo, no idea why => do not remove just update metadata.txt!

**Comment by pigreco** [comment]
@luipir it works, thanks !!!
![image](https://user-images.githubusercontent.com/7631137/41846867-67ad96ba-7878-11e8-854f-a2fe68d3bb64.png)
