### ISSUE TITLE
OSX - QGIS 3.2.0 and QMS 0.19.10 - Can't Use/Find Icon

### ISSUE THREAD

**Issue by dnseminara** [nextgis/quickmapservices#172]
Plugin is installed...

![screen shot 2018-07-02 at 10 35 30 am](https://user-images.githubusercontent.com/6739893/42178054-cdcacb32-7de3-11e8-90bc-1ae4feb5c941.png)

Icon does not appear in any of the toolbars or dropdown menu...

![screen shot 2018-07-02 at 10 38 14 am](https://user-images.githubusercontent.com/6739893/42178182-38d41d66-7de4-11e8-9103-c07a938e44ec.png)
![screen shot 2018-07-02 at 10 36 58 am](https://user-images.githubusercontent.com/6739893/42178196-497c1420-7de4-11e8-8bc5-0090ac3c75c9.png)
![screen shot 2018-07-02 at 10 37 51 am](https://user-images.githubusercontent.com/6739893/42178235-65aa1818-7de4-11e8-9720-a516c0f0b9b3.png)

Followed most of the steps in #158 ...

**Comment by brylie** [comment]
For me, I had to both *install* and then *activate* the plugin (by clicking the checkbox):

![screenshot_20180703_105253](https://user-images.githubusercontent.com/17307/42206245-3f79fb60-7eaf-11e8-9db9-b5c0e5ed09bc.png)

Then, the QuickMapServices is available under the **Web** -> **QuickMapServices** menu:
![screenshot_20180703_105427](https://user-images.githubusercontent.com/17307/42206327-77af0d18-7eaf-11e8-9b03-ba5035880617.png)

**Comment by simgislab** [comment]
right, you can't use plugin without turning it on

**Comment by brylie** [comment]
Yep. It just might not be obvious that installing doesn't also activate. E.g. when I install something from the KDE software center, it is ready to use immediately (same applies to other package managers).

**Comment by dnseminara** [comment]
@brylie - that did it, thanks! On OSX (or at least my version) there's no checkbox per-say, but double clicking does the trick!

![](http://g.recordit.co/4tEqnYeRVJ.gif)
