### ISSUE TITLE
quickmapservices implicated in crashes of QGIS 3.2 on Macs

### ISSUE THREAD

**Issue by rful011** [nextgis/quickmapservices#173]
A number of people have reported 3.2 crashing on startup - in all cases removing the profile allows QGIS to start.  Using quickmapservices plugin seems to be a common factor.

More more details here:

https://issues.qgis.org/issues/19314

https://gis.stackexchange.com/questions/288129/qgis-3-2-crashes-on-startup-on-mac-os

Adding QMS to the new  profile works OK at least for me.

**Comment by simgislab** [comment]
latest version of QMS I assume?

**Comment by jmarchand-jive** [comment]
I have also seen that issue, initially when upgrading from 3.0.2 to 3.2. I eventually removed the profile and continued working, then updated QMS to the latest version. Yesterday, it happened again, so I think we can safely conclude that it does happen with 0.19.10.1.

**Comment by simgislab** [comment]
please reopen if problem persists
