### ISSUE TITLE
Cannot activate QuickMapServices plugin in QGis 3.2

### ISSUE THREAD

**Issue by irenedelatorre** [nextgis/quickmapservices#174]
I'm a user of QGis, but this is the first time that I have it installed in a MAC (Sierra 10.12.6). I just installed the new version and I'm trying to install the plugins I usually use. QuickMapServices, gives me the following error when I try to activate it:

> Couldn't load plugin 'quick_map_services' due to an error when calling its classFactory() method
> 
> TypeError: 'QVariant' object is not subscriptable Traceback (most recent call last): File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 337, in startPlugin plugins[packageName] = package.classFactory(iface) File "/Users/delati01/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/init.py", line 35, in classFactory return QuickMapServices(iface) File "/Users/delati01/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/quick_map_services.py", line 72, in init self.locale = Locale.get_locale() File "/Users/delati01/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/plugin_locale.py", line 30, in get_locale return QSettings().value('locale/userLocale')[0:2] TypeError: 'QVariant' object is not subscriptable
> 
> Python version: 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] QGIS version: 3.2.0-Bonn Bonn, exported
> 
> Python Path: /Applications/QGIS3.app/Contents/MacOS/../Resources/python /Users/delati01/Library/Application Support/QGIS/QGIS3/profiles/default/python /Users/delati01/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins /Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins /Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6 /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages /Users/delati01/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by arthuragone** [comment]
Same bug in QGIS 3.4.1 Windows 10 64 bits

> Impossible de charger l'extension 'quick_map_services' provoque une erreur lors de l'appel à sa méthode classFactory() 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/AVIGNACQ/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\__init__.py", line 35, in classFactory
    return QuickMapServices(iface)
  File "C:/Users/AVIGNACQ/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\quick_map_services.py", line 72, in __init__
    self.locale = Locale.get_locale()
  File "C:/Users/AVIGNACQ/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\plugin_locale.py", line 30, in get_locale
    return QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable


Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.4.1-Madeira Madeira, 383851c597 

Chemin Python :
C:/OSGEO4~1/apps/qgis/./python
C:/Users/AVIGNACQ/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/AVIGNACQ/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/AVIGNACQ/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by fgoral** [comment]
I have the same problem, fresh install on Win10 64-bit, QGIS 3.4.2. 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/fgoral/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\__init__.py", line 35, in classFactory
    return QuickMapServices(iface)
  File "C:/Users/fgoral/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\quick_map_services.py", line 72, in __init__
    self.locale = Locale.get_locale()
  File "C:/Users/fgoral/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\plugin_locale.py", line 30, in get_locale
    return QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable


Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.4.2-Madeira Madeira, 22034aa070 

Python-Pfad:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/fgoral/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/fgoral/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/fgoral/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by 514ckw4r3** [comment]
Fixed in version 0.19.24. The fix will be available for download in the next release.
