### ISSUE TITLE
"plugin broken" - QuickMap Services

### ISSUE THREAD

**Issue by macdonaldrob** [nextgis/quickmapservices#175]
Hi, im using QGIS 2.18.23 and have used quickmapservices a lot, but last week it told me the plugin was nbroken (with the following code)

I've tried re-installing multiple times but no luck - does anyone know what the issue is? 

Thanks in Advance
Robbie

couldn't load plugin processing due to an error when calling its classFactory() method 

ImportError: cannot import name uic 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing\__init__.py", line 37, in classFactory
    from processing.ProcessingPlugin import ProcessingPlugin
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing\ProcessingPlugin.py", line 38, in 
    from processing.gui.ProcessingToolbox import ProcessingToolbox
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing\gui\ProcessingToolbox.py", line 31, in 
    from qgis.PyQt import uic
ImportError: cannot import name uic

Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.23 Las Palmas, 33e81905f4 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python
C:/Users/rajma/.qgis2/python
C:/Users/rajma/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/rajma/.qgis2//python
C:\Users\rajma\.qgis2\python\plugins\QuickMultiAttributeEdit/forms

**Comment by BishopGIS** [comment]
It seems to me the same issue as reported here: https://gis.stackexchange.com/q/234331/9904

**Comment by macdonaldrob** [comment]
@BishopGIS thanks for the quick response - I'll give that a try

**Comment by macdonaldrob** [comment]
Sorted - this worked for me. Thanks again.

**Comment by BishopGIS** [comment]
Reported as fixed
