### ISSUE TITLE
failed to add quickmapservices plugin on qgis 2.14.9 - the plugin is broken

### ISSUE THREAD

**Issue by jonatr** [nextgis/quickmapservices#181]
![image](https://user-images.githubusercontent.com/11156868/50435985-5ef61380-08ec-11e9-9623-820e37575ed0.png)

**Comment by simgislab** [comment]
any chance to update your QGIS?

**Comment by jonatr** [comment]
Oh, I thought I was reporting this as a good citizenship thing, it wasn't a
complaint...

If the only solution is to upgrade the qgis version, that's ok, I'll use a
different solution (I have 2 computers, one with internet, and one
standalone. As the stand-alone has 2.14.9 and cannot be upgraded, and thats
why I have 2.14.9 on the internet computer (so I can compare).

Thank you anyway...

Yonatan
