### ISSUE TITLE
QMS search should use QGIS proxy settings if set

### ISSUE THREAD

**Issue by alexmeseguer** [nextgis/quickmapservices#183]
Hi, when I insert for example "google" in the Search QMS, it shows an error:

Error of processing! ProxyError: HTTPSConnecctionPool(host='qms.nextgis.com', port=443):
Max retries exceeded with url: //api/v1/geoservices?search=goo&http=xxxxx%3xxxxxx.....(Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))

My proxy introduced in setting is correct and it is working because I can download this plugin correctly.

What's happen? Could you help me?

Thanks, best regards!

**Comment by simgislab** [comment]
QMS search seems to be ignoring QGIS proxy settings

**Comment by penguinchicago** [comment]
I'm seeing the same problem. Didn't happen in prior versions; I'm in 3.6.

**Comment by 514ckw4r3** [comment]
Fixed in 0.19.16

**Comment by Ennahoy** [comment]
Is 0.19.16 correct?
I have had this problem as well and looked  to update to the version you mention but the latest current version is 0.19.11

Please clarify

**Comment by simgislab** [comment]
yes, it's correct. You need to wait a bit for a public release

**Comment by Ennahoy** [comment]
Ok, thanks. Do you know an approximate release schedule?

**Comment by simgislab** [comment]
new version was released today https://twitter.com/nextgis/status/1399997343798333440

if you'd like to follow our news the best way is ![telegram](https://t.me/nextgis) or twitter
