### ISSUE TITLE
Call to qms.nextgis.com:443 hangs QGIS when proxy not yet set

### ISSUE THREAD

**Issue by rduivenvoorde** [nextgis/quickmapservices#187]
When QGIS starts and loads it plugins, apparently quickmapservices plugin pings back to qms.nextgis.com. (see screenshot):

![gnome-shell-screenshot-viimxz](https://user-images.githubusercontent.com/731673/53324218-911df480-38e0-11e9-847c-4bcae5a1a805.png)

Apparently this is done in the init or at least the part that QGIS loads when it is starting up.
If you are behind a enterprise proxy, which is not yet configured in QGIS, QGIS hangs on startup untill the timeout (with me 2 minutes because I do some other long loading wfs requests).
So it would be nice if this 'ping back' call could be done later (after the starting of QGIS? Maybe the moment a user actually uses the plugin?)

**Comment by 514ckw4r3** [comment]
Added request timeout ( 5s for connect and 20s for read) in 0.19.25. New version will be available for download in the next release.
