### ISSUE TITLE
Can't download due to certificate error

### ISSUE THREAD

**Issue by mossrussell** [nextgis/quickmapservices#188]
When trying to install the plugin, a student of mine has run into the following error: 

SSL errors occured accessing URL:  https://plugins.qgis.org/plugins/plugins.xml?qgis=3.4
* Unable to Get Local Issuer Certificate: The issuer certificate of a locally looked up certificate could not be found

It seems to be a server error?

**Comment by simgislab** [comment]
this is not related to plugin itself
