### ISSUE TITLE
Configure list of services

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/quickmapservices#19]
It will become difficult to work with large number of services. We can add a configuration page where it will be possible to hide/unhide a service and load/save user profiles.

**Comment by simgislab** [comment]
This should probably go along with a form to add/remove user services locally, #41

**Comment by simgislab** [comment]
New tab or new dialog to list current services and checkbox to show/hide services from the menu/toolbar.

Whether service is Base/Contributed/User should be indicated in a separate column.

**Comment by simgislab** [comment]
implemented in a slightly different way

**Comment by cpo-ux** [comment]
I know about the visibility option however I'd like to know how to go about removing an entry (group or service) from the list?  I see the paths where QGIS has stuff stored in AppData path on my windows machine but I don't know where to start editing or deleting stuff without breaking things.  I ended up uninstalling the plugin, then deleting the leftover files in:
AppData\Roaming\QGIS\QGIS3\profiles\default\QuickMapServices\Contribute 

and then reinstalling plugin to get rid of them (contributed pack) but it would be nice if there was a more convenient solution.  Thanks!
