### ISSUE TITLE
Open Sea Map - Seamarks not loading in QGIS 3.6.1

### ISSUE THREAD

**Issue by zking90** [nextgis/quickmapservices#190]
Hi I noticed when I try to pull up the Open Sea Map - Seamarks in QGIS 3.6.1 it is not loading, looks like it is but takes forever and shows no results, then causes the program to crash.

**Comment by BishopGIS** [comment]
On NextGIS QGIS 19.1 not reproduced.

<img width="991" alt="Снимок экрана 2019-04-04 в 22 07 12" src="https://user-images.githubusercontent.com/1708122/55581677-2903cf00-5726-11e9-8d8b-ce991c00773f.png">

**Comment by zking90** [comment]
Hi it doesn't look like you are using QGIS 3.6.1 only like I am.

**Comment by zking90** [comment]
![2019-04-04_15h17_02](https://user-images.githubusercontent.com/49288638/55582166-c93d0200-56ec-11e9-9d52-c287e50860a9.png)
![2019-04-04_15h17_41](https://user-images.githubusercontent.com/49288638/55582189-d78b1e00-56ec-11e9-8356-c2520c040f97.png)
At the bottom you can see the loading bar working but it never loads.

**Comment by simgislab** [comment]
better not use catalog, Seamarks found by searching - works
