### ISSUE TITLE
Bug with QMS and Google Road View in QGIS: Language change at different zoom level

### ISSUE THREAD

**Issue by netomnia** [nextgis/quickmapservices#194]
When I use QSM in QGIS 3.8, the language of the map changes...London ends up being Londres (French) at a specific Zoom Level.

It must be linked to the fact that I am French but I can't find a way to change it...

![London](https://user-images.githubusercontent.com/52371981/60394707-9efab500-9b20-11e9-97c6-6ce20c892c7c.png)
<img width="919" alt="Londres" src="https://user-images.githubusercontent.com/52371981/60394709-a28e3c00-9b20-11e9-9b12-63e913632be9.png">

**Comment by simgislab** [comment]
this has nothing to do with QMS itself

**Comment by netomnia** [comment]
Where do you think is the issue?

**Comment by simgislab** [comment]
check the TMS link, check the source, may be it is adjusting to your ip, etc.

in any case QMS shows what provider provides

**Comment by netomnia** [comment]
Hum...Not an IP issue, it is happening at 1 zoom/scale level only (if I zoom in or out, then it reverts back to English).

Thank you for your help
