### ISSUE TITLE
Mapsurfer update not merged yet

### ISSUE THREAD

**Issue by nilsnolde** [nextgis/quickmapservices#195]
Not sure when the current QMS version was released as there's no release tag for it. However, the crucial update to Mapsurfer wasn't released to the plugin repo yet : #185 , so that's not usable since then.

Could you please package some snapshot after that PR and release? Would be much appreciated.

**Comment by nilsnolde** [comment]
Any opinion here?

**Comment by nilsnolde** [comment]
Hm, really starting to wonder about the status of this repository. Sorry mate, don't see another option: @simgislab, can you please comment if you'll (dis)continue support for QMS or what the rough plan is?

**Comment by simgislab** [comment]
Hello, wouldn't call it discontinued. Will try to push an update soon.

**Comment by simgislab** [comment]
released on Dec, 3
