### ISSUE TITLE
Search error when working through proxy server

### ISSUE THREAD

**Issue by justkrevedko** [nextgis/quickmapservices#199]
Hello.

I get an error during QMS-search with enabled user's PATH variable 'http_proxy', 
![image](https://user-images.githubusercontent.com/175383/66629491-91b69180-ec0a-11e9-87da-292f1e8eb484.png)
After removing PATH variable there is a ValueError:
![image](https://user-images.githubusercontent.com/175383/66629535-b90d5e80-ec0a-11e9-9537-73ef23fa7f8a.png)
However, 'http_proxy' variable is needed for the correct work with OSM in InfraWorks. 
I can add/delete this variable by running simple script, but after it was created the first time - I can't get rid of the ValueError (Re-installing Plugin and Re-creating qgis profile doesn't help)

qgis - 3.8.3
qms - 0.19.10.1
os - Windows 10

**Comment by 514ckw4r3** [comment]
@justkrevedko, please verify this issue in the last release

**Comment by 514ckw4r3** [comment]
Closed due to lack of feedback, reopen if necessary
