### ISSUE TITLE
Порядок слоев в запросе к WMS

### ISSUE THREAD

**Issue by SergeyRyzhkov** [nextgis/quickmapservices#20]
В настройках сервиса (в ini-файле) указано
[wms]
url=http://maps.rosreestr.ru/arcgis/services/Cadastre/CadastreWMS/MapServer/WMSServer
params=format=image/png32&crs=EPSG:3857
layers=7,6,5,4,3,2,1

А запрос идет с порядком слоев 1,2,3,4,5,6,7 - то есть наоброт.

**Comment by drnextgis** [comment]
В https://github.com/nextgis/quickmapservices/commit/158c4abeb8a1cfb402cbda5d5407b1486f8251bc добавлена возможность поменять порядок следования слоёв.

**Comment by yellow-sky** [comment]
В секцию 'wms' нужно добавить параметр 'turn_over' = True. Тогда порядок будет обратным.

**Comment by SergeyRyzhkov** [comment]
Не совсем понял. А почему сразу "правильно" не сделать?
Если я задал порядок 1,2,3 в настройках, зачем делать в запросе 3,2,1 ?

**Comment by yellow-sky** [comment]
Тут есть проблема в самом QGIS: http://hub.qgis.org/issues/3819

27 февраля 2015 г., 13:20 пользователь Sergey Ryzhkov <
notifications@github.com> написал:

> Не совсем понял. А почему сразу "правильно" не сделать?
> Если я задал порядок 1,2,3 в настройках, зачем делать в запросе 3,2,1 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/quickmapservices/issues/20#issuecomment-76370795>
> .
>



-- 

Best regards,

Nikulin Eugeny
