### ISSUE TITLE
QGIS 3.10.0 - not reinstallable/usable in newest release

### ISSUE THREAD

**Issue by wmeinolf** [nextgis/quickmapservices#201]
With reference to #200 I confirm, that the plugin is not installable under 3.10.0 in case, QGIS CPU or GPU acceleration in turned on.
I have the same issue. I found, that the plugin can be installed as long as QGIS GPU acceleration is off. To reproduce, either install plugin with GPU acceleration switched on, or install plugin while GPU acceleration is turned off. Then turn acceleration on in QGIS settings, open plugin installer, select "installed plugins" and toggle tick box in front of "Quickmapservices" off and on. As soon as it's turned on while acceleration is also enabled, the following error message pops up (sorry for the German UI, I think it's similar to initially reported text.

I installed QGIS via OSGEO4W, ner user profile on Windows 10 all upgrades installed

--------------------
Konnte Erweiterung 'quick_map_services' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\meinotest/python/plugins\quick_map_services\__init__.py", line 35, in classFactory
    return QuickMapServices(iface)
  File "C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\meinotest/python/plugins\quick_map_services\quick_map_services.py", line 72, in __init__
    self.locale = Locale.get_locale()
  File "C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\meinotest/python/plugins\quick_map_services\plugin_locale.py", line 30, in get_locale
    return QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.10.0-A CoruÃ±a A CoruÃ±a, 6c816b4204 

Python-Pfad:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\meinotest/python
C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\meinotest/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/WMeinolf/AppData/Roaming/QGIS/QGIS3\profiles\meinotest/python
C:\Users\WMeinolf\AppData\Roaming\QGIS\QGIS3\profiles\meinotest\python\plugins\mmqgis/forms
C:\Users\WMeinolf\AppData\Roaming\QGIS\QGIS3\profiles\meinotest\python\plugins

**Comment by bong0** [comment]
If you refer to OpenCL acceleration: The same issue is present for me on macOS 10.15.4 and Qgis 3.10.5 **without** OpenCL acceleration (I don't have such a graphics card)

**Comment by simgislab** [comment]
is this still an issue with current QGIS 3.18.x?

the error message tells about locale problem, not sure how GPU is related

**Comment by wmeinolf** [comment]
I forgot about this, sorry. It works well since quite a while.
