### ISSUE TITLE
Is it possible to add satellite image date?

### ISSUE THREAD

**Issue by Saitodepaula** [nextgis/quickmapservices#202]
Would it be possible to add satellite image date, like from satellite images from Google and Bing?

Bing used to have a service for it, but unfortunately, it doesn't work anymore, but there is a Github page of it, maybe it can be used?

https://wiki.openstreetmap.org/wiki/Bing_imagery_analyzer_for_OSM

https://github.com/mvexel/bingimageanalyzer

https://mvexel.dev.openstreetmap.org/bing/

**Comment by AlisterH** [comment]
Go to:
QuickMapServices Settings > More services > Get contributed pack

**Comment by simgislab** [comment]
you need to find a particular service (if such exist) and publish it with qms.nextgis.com
