### ISSUE TITLE
Bugs in QGIS 3.10.x

### ISSUE THREAD

**Issue by moebi74** [nextgis/quickmapservices#203]
1. Since QGis 3.10.1 (including actual release 3.10.2) the online images of saved projects are not shown in the view - one has to add the images again to be able to view them

2. Since QGis 3.10.1 (including actual release 3.10.2) the added online images are not shown in the layouts and therefor not printable - no matter what you do

**Comment by simgislab** [comment]
saving and restoring services added by QMS works well in current 3.18 and 2.x
