### ISSUE TITLE
Remove items from list of services

### ISSUE THREAD

**Issue by cpo-ux** [nextgis/quickmapservices#205]
Hi, first of all thanks for the great plugin and great open catalog of geodata sources!

I know about the visibility option however I'd like to know how to go about removing an entry (group or service) from the list? I see the paths where QGIS has stuff stored in AppData path on my windows machine but I don't know where to start editing or deleting stuff without breaking things. I ended up uninstalling the plugin, then deleting the leftover files in:
AppData\Roaming\QGIS\QGIS3\profiles\default\QuickMapServices\Contribute

and then reinstalling plugin to get rid of them (contributed pack) but it would be nice if there was a more convenient solution. Thanks!

---------------------------------------------------------
implemented in a slightly different way

_Originally posted by @simgislab in https://github.com/nextgis/quickmapservices/issues/19#issuecomment-195342220_
----------------------------------------------------------------

**Comment by simgislab** [comment]
if contributed pack stuff is kept at all such functionality will create a headache to sync new 'official' releases of contrib pack and locally modified ones (if lets say such functionality will be introduced)

we need to have a go at finally removing it altogether + add some functionality to create user lists of services
