### ISSUE TITLE
If I set a keyboard shortcut for "set proper scale" it doesn't work

### ISSUE THREAD

**Issue by AlisterH** [nextgis/quickmapservices#206]
Is there something not quite right about how you set up the plugin's actions?
If I set a keyboard shortcut (Settings>Keyboard shortcuts) for "set proper scale", it doesn't work, and the shortcut isn't displayed in the menu.  I also tried setting a shortcut for the QMS "about" dialog and it doesn't work.  
I can successfully set keyboard shortcuts for other plugins' menu entries (e.g. I tested with the "Customize toolbars" plugin's "about", and the shortcut works and is displayed in the menu).

**Comment by 514ckw4r3** [comment]
Fixed in version 0.19.24. The fix will be available for download in the next release.
