### ISSUE TITLE
Quick Map services is not showing in Web option even it was installed 

### ISSUE THREAD

**Issue by rahulnet06** [nextgis/quickmapservices#208]
![Screenshot (207)](https://user-images.githubusercontent.com/66663448/84258521-b2860c80-ab34-11ea-86d8-51eef5681352.png)
![Screenshot (206)](https://user-images.githubusercontent.com/66663448/84258533-b74ac080-ab34-11ea-8167-198076b87176.png)
Hello,

I have installed the **QGIS 3.10.6 version 32-bit** and I also installed _**quickmapservices plugin.**_ Although it is switched on, it is not showing on my window in Web option below the meta search option. Please help me with this problem.

**Comment by oquintez** [comment]
Hola  rahulnet06, que solución tuviste a tu problema? experimento lo mismo.

**Comment by vmtorres05** [comment]
Hola buen día, quisiera saber si alguien pudo solucionar este problema, presento el mismo y no puedo ver el complemento de quickmapservices

**Comment by MarcialCosme** [comment]
Hello, I have the same problem. Could you tell us how to fix it, please?? Thank you so much!

**Comment by vvoodtroll** [comment]
Hello! 
Try this 
https://gis.stackexchange.com/questions/352661/quick-map-services-not-appearing-in-web-dropdown-menu

**Comment by simgislab** [comment]
Currently, by default in QGIS 3.x QMS appears on Manage Layers Toolbar, but not at Web menu.

This is a bug.

QMS should appear in the Web menu by default and should treat "Move to Manage layers panel" setting correctly (@514ckw4r3 )

![](http://m-d.me/img/ss/20210519_071041.png)

**Comment by 514ckw4r3** [comment]
Fixed in 0.19.16: Removed the 'Move plugin to Manage Layers panel' option from the settings. QMS is now only displayed in the Web menu.
