### ISSUE TITLE
AttributeError: module 'sys' has no attribute 'exc_type' 

### ISSUE THREAD

**Issue by TiagoVieiraBotany** [nextgis/quickmapservices#210]
Hello,

I just installed the plugin, but I can't add new map servers by the following "settings/ More services/ get contributed pack".

The following error message pops up:
------------------------------------------------------------------
AttributeError: module 'sys' has no attribute 'exc_type' 
Traceback (most recent call last):
  File "C:/Users/Tiago/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\settings_dialog.py", line 127, in get_contrib
    ExtraSources().load_contrib_pack()
  File "C:/Users/Tiago/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\extra_sources.py", line 87, in load_contrib_pack
    self._download_file(CONTRIBUTE_ZIP_DIRECT_URL, zip_file_path)
  File "C:/Users/Tiago/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\extra_sources.py", line 116, in _download_file
    reply = self.__sync_request(url)
  File "C:/Users/Tiago/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\extra_sources.py", line 145, in __sync_request
    raise Exception(error)
Exception: 99

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Tiago/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\settings_dialog.py", line 135, in get_contrib
    error_message = self.tr('Error on getting contrib pack: %s %s') % (sys.exc_type, sys.exc_value)
AttributeError: module 'sys' has no attribute 'exc_type'

Versão do Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versão do QGIS: 3.10.4-A Coruña A Coruña, 10bc9f2ff2 

Caminho do Python:
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/Tiago/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Tiago/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Tiago/AppData/Roaming/QGIS/QGIS3\profiles\default/python

------------------------------------------------------------------------------

I would like to use the googlemaps server.

Best rergards

**Comment by TiagoVieiraBotany** [comment]
It was a proxy issue actually! Sorry for that.
Cheers

**Comment by vlicks** [comment]
> It was a proxy issue actually! Sorry for that.
> Cheers

Hey Tiago, I am having the same problem! How did you fix it? 
Thanks!

**Comment by TiagoVieiraBotany** [comment]
Hi vlicks,
I was having an issue related to my university web server, which has a proxy configuration. Once I tried to use the plugin server by another internet connection (without proxy restrictions), it was ok. Good luck with that! Cheers.

**Comment by vlicks** [comment]
> Hi vlicks,
> I was having an issue related to my university web server, which has a proxy configuration. Once I tried to use the plugin server by another internet connection (without proxy restrictions), it was ok. Good luck with that! Cheers.

Thanks a lot, Tiago. I've tried again using a different connection and it magically worked!

**Comment by simgislab** [comment]
it's proxy or company network in 99% cases
