### ISSUE TITLE
QuickMapServices not showing any basemap

### ISSUE THREAD

**Issue by blacknightshade** [nextgis/quickmapservices#216]
I am using QGIS 3.16.0-Hannover and QuickMapServices (QMS) version 0.19.11.1. I have downloaded the contribution pack. All available basemaps are set as visible in the visibility folder. 
QMS was working while, all of a sudden, it stopped showing basemaps. I mean every basemaps available for QMS.

Maybe it's my fault because I could have changed some settings (and in the case Inexcuse) but I really do not know what to do.

Feel free to ask for more clarifications if needed.

Thanks in advance

**Comment by simgislab** [comment]
did you fix it?

**Comment by 514ckw4r3** [comment]
Closed due to lack of feedback
