### ISSUE TITLE
Error loading plugin when overriding locale in qgis_global_settings.ini

### ISSUE THREAD

**Issue by twerschlein** [nextgis/quickmapservices#217]
We override the user locale from the global-settings file (`globalLocale` is `de_CH`):

    "C:\Program Files\QGIS 3.10\apps\qgis-ltr\resources\qgis_global_settings.ini"    
    [locale]
    userLocale=en_US
    overrideFlag=true
    [...]

When installing the QuickMapServices plugin we get the following error:

    Couldn't load plugin 'quick_map_services' due to an error when calling its classFactory() method 
    
    TypeError: 'NoneType' object is not subscriptable 
    Traceback (most recent call last):
      File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
        plugins[packageName] = package.classFactory(iface)
      File "C:/Users/testuser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\__init__.py", line 35, in classFactory
        return QuickMapServices(iface)
      File "C:/Users/testuser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\quick_map_services.py", line 72, in __init__
        self.locale = Locale.get_locale()
      File "C:/Users/testuser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\plugin_locale.py", line 30, in get_locale
        return QSettings().value('locale/userLocale')[0:2]
    TypeError: 'NoneType' object is not subscriptable
    
    
    Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
    QGIS version: 3.10.14-A Coruña A Coruña, 8374282d2a 
    
    Python Path:
    C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
    C:/Users/testuser/AppData/Roaming/QGIS/QGIS3\profiles\default/python
    C:/Users/testuser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
    C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
    C:\PROGRA~1\QGIS3~1.10\apps\Python37
    C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
    C:\Program Files\QGIS 3.10\bin\python37.zip
    C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
    C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
    C:\Program Files\QGIS 3.10\bin
    C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
    C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
    C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
    C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
    C:/Users/testuser/AppData/Roaming/QGIS/QGIS3\profiles\default/python

The error is related to https://github.com/qgis/QGIS/issues/29281#issuecomment-568170871_ as reported by @haubourg : 

The installation only works, if the user overrides the locale manually from the GUI (Settings > Options > General > Override system locale), which creates the entries in the user's profile `QGIS3.ini` that the QuickMapServices plugin relies on: 

    "C:\Users\testuser\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\QGIS3.ini"    
    [...]
    [locale]
    overrideFlag=true
    globalLocale=de_CH
    showGroupSeparator=false
    userLocale=en_US

The workaround to start QGIS with `--lang en_US` bypasses the bug as well, but prevents the user from changing the language afterwards.

**Comment by 514ckw4r3** [comment]
Fixed in version 0.19.22. The fix will be available for download in the next release.
