### ISSUE TITLE
Use the quadkey in the open layers

### ISSUE THREAD

**Issue by nugaldea** [nextgis/quickmapservices#22]
Es posible usar el parámetro "quadkey" en la url ({q})?. En MOBAC el parámetro existe como {$q}.

**Comment by nugaldea** [comment]
You can use the parameter "quadkey" in the url ({q}) ?. In MOBAC parameter exists as {$ q}.

**Comment by simgislab** [comment]
Can you show full working example of the url?

**Comment by nugaldea** [comment]
Thanks. The example url is 
http://ak.t0.tiles.virtualearth.net/tiles/a{$q}.jpeg?g=2241&amp;n=z
the {$q} are the quadkey map.  Example: 
http://ak.t0.tiles.virtualearth.net/tiles/a032221.jpeg?g=2241&amp;n=z
this is the explain of the quadkey map: 
https://msdn.microsoft.com/en-us/library/bb259689.aspx
and in this page 
http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/ 
can see the example between xyz and quadkeys.

In the email send the file MobacSource.zip to use with Mobile Atlas 
Creator http://mobac.sourceforge.net/ (Add bingmaps, googlemaps and 
esrimaps to the mobac)
the file newgroups.zip have the groups of google maps and esri maps; and 
the file newdatasource.zip have the source to use google maps (3 
diferents maps) and esri maps (3 diferents maps), in the plugin. With 
new data sources your plugin will rise to openlayer plugins; which has 
problems with Projections.

Thank You. I appreciate your interest in my question.


El 19/03/2015 a las 01:27 p.m., Maxim Dubinin escribió:
>
> Can you show full working example of the url?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nextgis/quickmapservices/issues/22#issuecomment-83729235>.
>

-- 

Muchas Gracias

___________________
Nelson Ugalde Araya
nugaldea@gmail.com
nugalde@numar.net
85-27-04-83
27-85-91-32
27-81-10-98

**Comment by nugaldea** [comment]
Hi; i find a page with a code to do xyz  to quadkey

http://phpforum.de/forum/showthread.php?t=270158

function TileXYToQuadKey($tileX, $tileY, $levelOfDetail) {
$quadKey = '';
for ($i = $levelOfDetail; $i > 0; $i--) {
$digit = '0';
$mask = 1 << ($i - 1);
if (($tileX & $mask) != 0) {
$digit++;
}
if (($tileY & $mask) != 0) {
$digit++;
$digit++;
}
$quadKey .= $digit;
}
return $quadKey;
}

echo TileXYToQuadKey(134926, 86121, 18);
// 120202111102203112

I test the example in the page http://www.maptiler.org/
google-maps-coordinates-tile-bounds-projection/ and are corrects the
numbers.

2015-03-19 19:43 GMT-06:00 Nelson Ugalde Araya <nugaldea@gmail.com>:

>  Thanks. The example url is http://ak.t0.tiles.virtualearth.net/tiles/a
> {$q}.jpeg?g=2241&amp;n=z
> the {$q} are the quadkey map.  Example:
> http://ak.t0.tiles.virtualearth.net/tiles/a032221.jpeg?g=2241&amp;n=z
> this is the explain of the quadkey map:
> https://msdn.microsoft.com/en-us/library/bb259689.aspx
> and in this page
> http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/
> can see the example between xyz and quadkeys.
>
> In the email send the file MobacSource.zip to use with Mobile Atlas
> Creator http://mobac.sourceforge.net/ (Add bingmaps, googlemaps and
> esrimaps to the mobac)
> the file newgroups.zip have the groups of google maps and esri maps; and
> the file newdatasource.zip have the source to use google maps (3 diferents
> maps) and esri maps (3 diferents maps), in the plugin. With new data
> sources your plugin will rise to openlayer plugins; which has problems
> with Projections.
>
> Thank You. I appreciate your interest in my question.
>
>
> El 19/03/2015 a las 01:27 p.m., Maxim Dubinin escribió:
>
> Can you show full working example of the url?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/quickmapservices/issues/22#issuecomment-83729235>
> .
>
>
> --
>
> Muchas Gracias
>
> ___________________
> Nelson Ugalde Arayanugaldea@gmail.comnugalde@numar.net
> 85-27-04-83
> 27-85-91-32
> 27-81-10-98
>
>


-- 
Muchas Gracias

___________________
Nelson Ugalde Araya
nugaldea@gmail.com
nugalde@numar.net
85-27-04-83
27-85-91-32
27-81-10-98

**Comment by yellow-sky** [comment]
Released in 10b58633664e7faf9ff98fc49d1cb00569f7ded2
