### ISSUE TITLE
Issues when installing QuickMapServices QGIS plugin

### ISSUE THREAD

**Issue by FabioDioguardi** [nextgis/quickmapservices#224]
I am trying to install the QuickMapServices QGIS (v3.8.12) plugin. The installation crashes with the following error messages:

Couldn't load plugin 'quick_map_services' due to an error when calling its classFactory() method 
TypeError: object of type 'QVariant' has no len() 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/fabiod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\__init__.py", line 35, in classFactory
    return QuickMapServices(iface)
  File "C:/Users/fabiod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\quick_map_services.py", line 72, in __init__
    self.locale = Locale.get_locale()
  File "C:/Users/fabiod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\plugin_locale.py", line 30, in get_locale
    if len(locale) > 2:
TypeError: object of type 'QVariant' has no len()

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.18.2-Zürich Zürich, 515138c171 
Python Path:
•	C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python
•	C:/Users/fabiod/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/fabiod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python/plugins
•	C:\PROGRA~1\QGIS3~1.18\apps\Python37
•	C:\PROGRA~1\QGIS3~1.18\apps\Python37\Scripts
•	C:\Program Files\QGIS 3.18\bin\python37.zip
•	C:\PROGRA~1\QGIS3~1.18\apps\Python37\DLLs
•	C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib
•	C:\Program Files\QGIS 3.18\bin
•	C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages
•	C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\win32
•	C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\Pythonwin
•	C:/Users/fabiod/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\fabiod\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\flo2d\deps\pyqtgraph-0.10.0-py3.6.egg

**Comment by 514ckw4r3** [comment]
@FabioDioguardi @GotitadeLuna, this issue fixed in 0.19.27. Update is available for download. Reopen if necessary.
