### ISSUE TITLE
Is there any way of taking out the labels from the "Google.cn Normal" map? 

### ISSUE THREAD

**Issue by ramuyk** [nextgis/quickmapservices#225]
I've extracted a raster layer from the `Google.cn Normal` map, but in my specific case having the labels and icons is a problem for me. The map that I need is the following one, but without the labels:

![Screenshot_20211129_164744](https://user-images.githubusercontent.com/44415096/143933295-e413c94a-ade0-4359-996f-f8bad8f43e78.png)

I've realized that there's a map that shows only the labels:

![Screenshot_20211129_164815](https://user-images.githubusercontent.com/44415096/143934119-1034756d-7668-4307-bf74-6cefe1e8e250.png)

I'd like to do the opposite of this last image... I want to keep the `Google.cn Normal` map without its labels. Is there any tweak I can do to make it possible?

**Comment by simgislab** [comment]
This is a question for general QGIS forums and/or particular service providers.

Functionality to modify services is out of QMS plugin scope.
