### ISSUE TITLE
Error on getting contributed pack

### ISSUE THREAD

**Issue by sspp11** [nextgis/quickmapservices#226]
![2](https://user-images.githubusercontent.com/96287585/146520457-eb9f63cc-50e4-4e9a-8282-4d6bd9f71aae.PNG)

I succesfully installed QuickMapServices plugin but when I try to get the contributed pack I see 403 error.

How can I resolve this issue?

Thanks in advance

**Comment by MatPuche** [comment]
I have the same issue, with error 203, with QGIS Desktop 3.22.4.

**Comment by xandros76** [comment]
> I have the same issue, with error 203, with QGIS Desktop 3.22.4.

Hi, same here, 3.16.11-Hannover on Windows 10. Error 203.

**Comment by djmbwr** [comment]
I have same issue with error 203 on 3.22.4

**Comment by liuxsdev** [comment]
> I have same issue with error 203 on 3.22.4

`CONTRIBUTE_ZIP_DIRECT_URL = 'http://nextgis.ru/programs/qms/quickmapservices_contrib.zip'`

this url goes wrong , download from https://github.com/nextgis/quickmapservices_contrib and install pack manually

**Comment by xandros76** [comment]
Hi liuxdev, thank you for your reply.

> install pack manually

I found a file called quickmapservices_contrib-master.zip on that webpage, but I don't know how to install it manually. I looked on the webpage you said and inside the package for instructions but I got no ones.

**Comment by liuxsdev** [comment]
> Hi liuxdev, thank you for your reply.
> 
> > install pack manually
> 
> I found a file called quickmapservices_contrib-master.zip on that webpage, but I don't know how to install it manually. I looked on the webpage you said and inside the package for instructions but I got no ones.

open this path on explorer : ` C:\Users\<Yourname>\AppData\Roaming\QGIS\QGIS3\profiles\default\QuickMapServices\Contribute`

and unzip `quickmapservices_contrib-master.zip` 
copy  this two Folder `data_sources` and `groups`  to `Contribute` (override)

then restart QGIS

![image](https://user-images.githubusercontent.com/11004456/158132398-3ae26772-06a3-4240-8067-7273824c56fb.png)

**Comment by MatPuche** [comment]
Thank you Liuxsdev, it works!

**Comment by Adrian-hub8** [comment]
Thank you,, excellent it works!!!

**Comment by GITHUBAntoineDENIS** [comment]
Did you plan to solve the problem error 203 when trying to get contributed pack fromQMS GUI in QGIS?

**Comment by simgislab** [comment]
we're in process of fixing it

**Comment by simgislab** [comment]
please try new version 0.19.29

**Important: please be advised that 'contributed pack' is considered obsolete. We recommend to get familiar with QMS search both for using services and creating new ones. Expect this functionality (getting contrib pack) to completely disappear in following months. 

Check out video demo: https://www.youtube.com/watch?v=Kw8Ciz2VcAc

Thank you.**

**Comment by GITHUBAntoineDENIS** [comment]
OK THANK YOU! 
NOW IT IS WORKING. THE BUG IS SOLVED. (after  plugin update in QGIS)
Many Thanks !

**Comment by lpsfj** [comment]
> > Hi liuxdev, thank you for your reply.
> > > install pack manually
> > 
> > 
> > I found a file called quickmapservices_contrib-master.zip on that webpage, but I don't know how to install it manually. I looked on the webpage you said and inside the package for instructions but I got no ones.
> 
> open this path on explorer : ` C:\Users\<Yourname>\AppData\Roaming\QGIS\QGIS3\profiles\default\QuickMapServices\Contribute`
> 
> and unzip `quickmapservices_contrib-master.zip` copy this two Folder `data_sources` and `groups` to `Contribute` (override)
> 
> then restart QGIS
> 
> ![image](https://user-images.githubusercontent.com/11004456/158132398-3ae26772-06a3-4240-8067-7273824c56fb.png)

Thanks!!!!!!!!!!!!!
