### ISSUE TITLE
Is it possible to set the referer / referrer?

### ISSUE THREAD

**Issue by skitourenguru** [nextgis/quickmapservices#234]
Under the QMS-Settings its possible to Add a Custom Map. 
Is it also possible to configure a Referer? 
By the GUI its not possible, may be by configuring the data about the Custom Map!? But where are the data stored (under Windows/Linux)?

**Comment by simgislab** [comment]
you can find all QMS services settings here:

```%APPDATA%\QGIS\QGIS3\profiles\default\QuickMapServices\```
