### ISSUE TITLE
Проблема с загрузкой тайлов, у которых yOriginTop = 0

### ISSUE THREAD

**Issue by Vetaldp** [nextgis/quickmapservices#24]
Несмотря на наличие возможности в TileLayerPlugin, который используется в QuickMapServices, задать значение yOriginTop = 0 или 1, указание данного параметра в блоке [tms] файла metadata.ini не дает должного эффекта и, соответственно, тайлы не загружаются (например, с Публичной кадастровой карты Украины)

Содержание файла metadata.ini:

[general]
id = pkk_orto
type = TMS
is_contrib = False

[ui]
group = Публичная кадастровая карта Украины
alias = PKK OrtoPhoto
alias[ru] = Ортофотоплан М 1:10 000
icon = favicon.ico

[license]
name = 
link = http://map.land.gov.ua
copyright_text = © 2014 Всі права захищені. ЦДЗК. Версія 1.13.
copyright_link = 
terms_of_use = 

[tms]
url = http://212.26.144.110/tile2/orto_10000/{z}/{x}/{y}.jpg
yOriginTop = 0
zmax = 16

**Comment by yellow-sky** [comment]
Да, в нынешней версии обработка этого параметра не предназначена. В следующей версии добавим.

**Comment by Vetaldp** [comment]
Спасибо огромное! Если будет возможность, добавьте, пожалуйста, и обработку параметра "zmin"

**Comment by yellow-sky** [comment]
z_min уже есть в 0.11

**Comment by yellow-sky** [comment]
Пример с yOriginTop==0 есть в контрибе - ПКК Украины
