### ISSUE TITLE
Load of Google or Bing satellite causes QGIS crash on Ubuntu 22.04

### ISSUE THREAD

**Issue by Antoviscomi** [nextgis/quickmapservices#241]
Hi all,
I've Noticed that in 
QGIS | 3.28.2-Firenze | Revisione codice QGIS | b47e00ba60
when I try to load a satellite map by mean of QMS, QGIS shutdown without error messages

[Video del 01-09-2023 11:45:54 AM.webm](https://user-images.githubusercontent.com/12639444/211290706-bf2de922-d9e2-494b-9a2c-8820a667a9f2.webm)

**Comment by simgislab** [comment]
Hello, can you try to load the same from QMS search panel? Does it work?

See intro video on how to do it https://qms.nextgis.com/about

**Comment by Antoviscomi** [comment]
@simgislab I've noticed that I can load Google Label without chrashes from drop down list

**Comment by simgislab** [comment]
thanks, we'll test more to confirm

**Comment by Antoviscomi** [comment]
@simgislab for more details,
I click oh details from QNS search panel then on the page in screenshot I click on the 
URL: [https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}](https://mt1.google.com/vt/lyrs=s&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D)

![image](https://user-images.githubusercontent.com/12639444/211549399-c0d33d34-2ecc-40ad-9b71-b8f5d9ebff84.png)

I click on the 
URL: [https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}](https://mt1.google.com/vt/lyrs=s&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D)
this is the result
![Schermata del 2023-01-10 13-18-23](https://user-images.githubusercontent.com/12639444/211550346-98c1ea83-0489-4679-89bd-2c20bb4b3e37.png)

**Comment by simgislab** [comment]
this is normal this is a TMS link, it is not supposed to open in your browser directly

this information is not related to your original issue

**Comment by Antoviscomi** [comment]
ok @simgislab sorry

**Comment by Antoviscomi** [comment]
I add that Italy PCN services work well from QMS panel

**Comment by Antoviscomi** [comment]
@simgislab I close this issue because of the QMS now it works fine after a system update, so I think was a local issue

**Comment by simgislab** [comment]
thank you!
