### ISSUE TITLE
Perhaps there is a way to load historical google satellite imagery with  QuickMapServices plugin?

### ISSUE THREAD

**Issue by SevenTae** [nextgis/quickmapservices#244]
Some of the work I'm currently doing requires remote sensing imagery for different time periods，so is there any way to get remote sensing images for say 2022.Thank you so much.

**Comment by simgislab** [comment]
QMS plugin doesn't provide imagery, it provides a catalog that contains links to 3rd party services that provide imagery.

If you need to add something with QMS you need to make sure it exists in the catalog.

If it doesn't you need to add it to the catalog (if you know how and if it's possible at all).

https://qms.nextgis.com
https://qms.nextgis.com/faq
