### ISSUE TITLE
srtm ne fonctionne pas

### ISSUE THREAD

**Issue by etoile05dh** [nextgis/quickmapservices#247]
Bonjour,
Mon pluging srtm ne marche pas sur Qgis car on me met "connexion refusée " sans me donner le lien permettant de s'inscrire sur le site de la nasa.
Merci de m'aider

**Comment by simgislab** [comment]
Hello, not sure how this is related to QMS plugin

**Comment by etoile05dh** [comment]
> Hello, not sure how this is related to QMS plugin

Auriez-vous svp une idée d'où peut provenir l'erreur? Merci d'avance
