### ISSUE TITLE
Setting Quick Maps to new CRS

### ISSUE THREAD

**Issue by lennipenny** [nextgis/quickmapservices#249]
Hello everyone, 
I have been trying to set a new CRS for the base layer. I think I am making a really basic mistake, but whenever I use the warp tool it says:
<img width="644" alt="Bildschirmfoto 2024-03-11 um 20 35 34" src="https://github.com/nextgis/quickmapservices/assets/128855610/0ab27733-7f9b-4994-88a3-1f7247b2524b">
Is it even possible to reproject raster layers from Quick Map Services?
I hope you can help!

**Comment by simgislab** [comment]
Hello, this is not related to QMS plugin.
This is a question for GDAL's gdalwarp. I don't know it is possible to reproject the TMS link (i.e. the whold world). 

I'd guess not.
