### ISSUE TITLE
Добавить список субдоменов доступных тайловых серверов

### ISSUE THREAD

**Issue by ANAT01** [nextgis/quickmapservices#27]
Многие тайловые сервера имеют несколько субдоменов для скачивания тайлов, выглядит как:

```
a.tile.openstreetmap.org
b.tile.openstreetmap.org
c.tile.openstreetmap.org
```

В leaflet.js записывается как http://{s}.tile.openstreetmap.org/{z}/{x}/{y}

В QMS может выглядеть как то так:

```
url = http://[a,b,c].tile.openstreetmap.org/{z}/{x}/{y}
```

**Comment by simgislab** [comment]
пару лет назад сделали, работает
