### ISSUE TITLE
Layer disappears

### ISSUE THREAD

**Issue by drnextgis** [nextgis/quickmapservices#3]
Добавил слой OSM Mapnik style, включил преобразование координат на лету в 4326 - при уменьшении масштабного уровня слой пропадает.

**Comment by yellow-sky** [comment]
Перепроицирование будет работать, только если установлен пакет python-gdal. В твоей конфигурации он есть?

**Comment by drnextgis** [comment]
Есть, перепроецирование работает, но на определённом масштабе слой исчезает.

**Comment by yellow-sky** [comment]
А на каком? Количество уровней ограниченно. И ниже какого-то действительно
не отображает.

14 января 2015 г., 10:37 пользователь Denis Rykov <notifications@github.com>
написал:

> Есть, перепроецирование работает, но на определённом масштабе слой
> исчезает.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/quickmapservices/issues/3#issuecomment-69879308>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by drnextgis** [comment]
Похоже это связано со 180 меридианом, на одном и том же масштабе можно сдвинуть карту и она перестанет отображаться.

**Comment by yellow-sky** [comment]
Подтверждаю.
При включенном перепроицировании и переходе через 180 меридиан тайлы пропадают.

**Comment by simgislab** [comment]
все работает на нативном рендерере
