### ISSUE TITLE
Contributed pack can't be downloaded if behind the proxy

### ISSUE THREAD

**Issue by PFerro** [nextgis/quickmapservices#32]
I have this tracback when I try to get the “contributed pack”.
Do imagine why?

Traceback (most recent call last):
  File "C:/Users/pedro.ferro/.qgis2/python/plugins\quick_map_services\settings_dialog.py", line 86, in get_contrib
    error_message = self.tr('Error on getting contrib pack: %s %s') % (sys.exc_type, sys.exc_value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 50: ordinal not in range(128)

Versão do Python:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

Versão do QGIS:
2.8.1-Wien Wien, exported

Caminho para o Python: ['C:/Users/pedro.ferro/.qgis2/python/plugins\\processing', 'C:\\Users\\pedro.ferro\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\requests-2.0.1-py2.7.egg', 'C:\\Users\\pedro.ferro\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\python_dateutil-2.2-py2.7.egg', 'C:\\Users\\pedro.ferro\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\six-1.9.0-py2.7.egg', 'C:\\Users\\pedro.ferro\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\lxml-3.3.5-py2.7-win32.egg', 'C:\\Users\\pedro.ferro\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\gsimporter-0.2-py2.7.egg', 'C:\\Users\\pedro.ferro\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\httplib2-0.9-py2.7.egg', 'C:/OSGeo4W/apps/qgis/./python', u'C:/Users/pedro.ferro/.qgis2/python', u'C:/Users/pedro.ferro/.qgis2/python/plugins', 'C:/OSGeo4W/apps/qgis/./python/plugins', 'C:\\OSGeo4W\\bin\\python27.zip', 'C:\\OSGeo4W\\apps\\Python27\\DLLs', 'C:\\OSGeo4W\\apps\\Python27\\lib', 'C:\\OSGeo4W\\apps\\Python27\\lib\\plat-win', 'C:\\OSGeo4W\\apps\\Python27\\lib\\lib-tk', 'C:\\OSGeo4W\\bin', 'C:\\OSGeo4W\\apps\\Python27', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win32.egg', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\python_dateutil-2.2-py2.7.egg', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\pytz-2014.2-py2.7.egg', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win32.egg', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\six-1.6.1-py2.7.egg', 'C:\\OSGeo4W\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'C:/Users/pedro.ferro/.qgis2//python', 'C:\\Users\\pedro.ferro\\.qgis2\\python\\plugins\\opengeo\\ext-libs', 'C:\\Users\\pedro.ferro\\.qgis2\\python\\plugins\\QuickMultiAttributeEdit/forms', '.', 'C:\\OSGeo4W\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\Users\\pedro.ferro\\.qgis2\\python\\plugins\\mmqgis/forms']

**Comment by simgislab** [comment]
Hi, are you behind proxy by any chance?

**Comment by PFerro** [comment]
Yes.

Is that the problem?

**Comment by simgislab** [comment]
turns out it is, we're working on fixing it
