### ISSUE TITLE
Get Contributed Pack does not use QGIS proxy settings

### ISSUE THREAD

**Issue by rduivenvoorde** [nextgis/quickmapservices#35]
When using the plugin in an environment which uses a proxy to go outside, all layers are working fine.

But when you try to get the Contributed Pack, you will see the attached error

![urlliberror](https://cloud.githubusercontent.com/assets/731673/9932570/4d06d688-5d45-11e5-982b-bcc65de0ca09.png)

I had a problem like this in one of my own plugins, and received a patch to get the proxy settings from QGIS and use it in urllib2 lib, maybe it can be of use:

https://github.com/rduivenvoorde/pdokservicesplugin/blob/master/pdokgeocoder.py#L28-L45

**Comment by yellow-sky** [comment]
Duplicate #32
