### ISSUE TITLE
Нет перевода некоторых строк

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/quickmapservices#37]
![2015-09-20 17 30 36](https://cloud.githubusercontent.com/assets/1708122/9982051/af74a9f0-5fd7-11e5-9a3f-8b4510abe9de.png)

**Comment by simgislab** [comment]
в файле переводов есть кстати: 

https://github.com/nextgis/quickmapservices/blob/master/src/i18n/QuickMapServices_ru.ts#L142

может забыли qm сбилдить перед релизом?
