### ISSUE TITLE
Перемешивание тайлов с разных слоёв при отключении слоя

### ISSUE THREAD

**Issue by drnextgis** [nextgis/quickmapservices#38]
1. Создаём новый проект, добавляем слой OSM Mapnik
2. Зумим на г. Барнаул
3. Добавляем слой Генштаб - Топокарты (Маршруты.ру)
4. Отключаем слой OSM Mapnik. Однако некоторые фрагменты его тайлов остаются на канвасе.

![qms-qgis-bug-01](https://cloud.githubusercontent.com/assets/866124/9984568/8369bfba-6033-11e5-9ffb-c7de76b0d1cf.png)

**Comment by yellow-sky** [comment]
Если очистить сетевой кэш, проблема повторяется?

21 сентября 2015 г., 5:37 пользователь Denis Rykov <notifications@github.com
> написал:

>
>    1. Создаём новый проект, добавляем слой OSM Mapnik
>    2. Зумим на г. Барнаул
>    3. Добавляем слой Генштаб - Топокарты (Маршруты.ру)
>    4. Отключаем слой OSM Mapnik. Однако некоторые фрагменты его тайлов
>    остаются на канвасе.
>
> [image: qms-qgis-bug-01]
> <https://cloud.githubusercontent.com/assets/866124/9984568/8369bfba-6033-11e5-9ffb-c7de76b0d1cf.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/quickmapservices/issues/38>.
>



-- 

Best regards,

Nikulin Eugeny

**Comment by drnextgis** [comment]
А как его почистить, `~/.qgis2/cache` - это он?

**Comment by yellow-sky** [comment]
Можно в окне настроек qgis

2015-09-21 5:53 GMT+03:00 Denis Rykov <notifications@github.com>:

> А как его почистить, ~/.qgis2/cache - это он?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/quickmapservices/issues/38#issuecomment-141863379>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by drnextgis** [comment]
Почистил, теперь вроде нормально отображается. Это чей баг - QGIS или плагина?
![qgis-qms-bug-03](https://cloud.githubusercontent.com/assets/866124/9984724/588af11c-6036-11e5-9600-75e39b2820d5.png)

**Comment by yellow-sky** [comment]
Пока сложно сказать.
Возможно это баг кешатора тайлов, хотя он не имеет доступ к другим слоям.
С другой стороны это может быть проблема фонового кэша канваса, который
используется для ускорения рендеринга. Нужно проверять будет.

2015-09-21 5:57 GMT+03:00 Denis Rykov <notifications@github.com>:

> Почистил, теперь вроде нормально отображается. Это чей баг - QGIS или
> плагина?
> [image: qgis-qms-bug-03]
> <https://cloud.githubusercontent.com/assets/866124/9984724/588af11c-6036-11e5-9600-75e39b2820d5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/quickmapservices/issues/38#issuecomment-141863611>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by yellow-sky** [comment]
Попробуй отключи кэширование при отрисовке (Настройки -> Рендеринг -> Исп кэш для отрисовки, нужно перезагрузить qgis). Повторяется или нет?

**Comment by drnextgis** [comment]
А он у меня и так отключен. Более того, как я почистил кэш, проблема больше не воспроизводится.

**Comment by simgislab** [comment]
@drnextgis закрываем пока?

**Comment by drnextgis** [comment]
Давай пока закроем, если что - переоткрою.
