### ISSUE TITLE
В новом проекте проявляются данные с предыдущего

### ISSUE THREAD

**Issue by drnextgis** [nextgis/quickmapservices#39]
1. Добавляем слой OSM Mapnik (охват не меняем, на весь мир)
2. Проекты - Создать - Закрыть без сохранения
3. Добавляем слой Грузия - NG NAPR STREETS

На севере видно часть тайлов OSM.

![qgis-qms-bug02](https://cloud.githubusercontent.com/assets/866124/9984649/3f39bf6e-6035-11e5-801d-2cccef945864.png)

**Comment by drnextgis** [comment]
Очистка кэша никак не помогает.

**Comment by simgislab** [comment]
не воспроизводится

это явно не QMS проблема, все таки какой-то кэш

**Comment by simgislab** [comment]
@drnextgis закрываем?

**Comment by drnextgis** [comment]
Не знаю, у меня стабильно воспроизводится.

**Comment by simgislab** [comment]
reopen if necessary
