### ISSUE TITLE
Tiled layer CRS

### ISSUE THREAD

**Issue by pavelpromin** [nextgis/quickmapservices#4]
Add a parameter to metadata.ini to define base CRS for tile layers that use projection different from WGS84/pseudo merkator (epsg 3857).

**Comment by yellow-sky** [comment]
For [tms] section new params:
epsg_crs_id (int)
postgis_crs_id (int)
custom_proj (proj4 str)

**Comment by yellow-sky** [comment]
Only crs released! Custom tile scheme not supports!

**Comment by MatzFan** [comment]
I'm considering trying a PR to add custom tile scheme functionality (as per yellow-sky's last comment). Before I do so, could you confirm that you would be willing to incorporate this (if it works!) and point me at the file(s) that may need amending - here for a start I guess: https://github.com/nextgis/quickmapservices/blob/master/src/py_tiled_layer/tiles.py

**Comment by simgislab** [comment]
sure, will be happy to merge if all is fine, here is the ticket: #52

**Comment by yellow-sky** [comment]
MatzFan, this is the right file to get started. Try to create custom service and try to change settings - 
https://github.com/nextgis/quickmapservices/blob/master/src/py_tiled_layer/tiles.py#L81
