### ISSUE TITLE
Being able to add and remove an own webservice (URL)

### ISSUE THREAD

**Issue by sfkeller** [nextgis/quickmapservices#41]
I'd wish to be able to add an own webservice (URL) - especially an ArcGIS Map Service - to the list. That could be a simple URL text input. In addition, it should be possible to remoce list items.

BTW: We have jus released an ArcGIS Feature Service reader plugin: http://plugins.qgis.org/plugins/connector/

**Comment by simgislab** [comment]
1. If your service is stable and potentially interesting for many, please consider adding it to our list of contributed services. It's easy and sort of more permanent https://github.com/nextgis/quickmapservices_contrib
2. Having a simple form to add services to current list sounds good, we'd welcome pull-request on that.
3. Configuration of current list of services to hide/unhide them was already mentioned, see #19

**Comment by sfkeller** [comment]
There are many services which aren't meant as public base map services; they are rather part of an internal infrastructure. For these it makes no sense of being added to the list of contributed services. That's why I suggested adding and removing services (locally).

**Comment by simgislab** [comment]
I totally understand, I was just making sure you're aware of this option. Thanks for your feedback.

**Comment by simgislab** [comment]
New button 'Add service' in Manage services - opens up a form to be filled, on save - adds a data_source in /home/sim/.qgis2/QuickMapServices/User

**Comment by sfkeller** [comment]
Cool! Waiting for this feature so that it can be updated inside QGIS.

Just another related feature request: Is it possible to load also raster MBTiles (.mbtiles) to be used locally and offline? See e.g. the downloadable files from OSM2VectorTiles project (http://osm2vectortiles.org/downloads/ ).

**Comment by simgislab** [comment]
Re: [quickmapservices] Being able to add and remove an own webservice (URL) (#41)


can you please make a new issue

Вы писали 15 января 2016 г., 11:42:32:





Cool! Waiting for this feature so that it can be updated inside QGIS.
Just another related feature request: Is it possible to load also raster MBTiles (.mbtiles) to be used locally and offline? See e.g. the downloadable files from OSM2VectorTiles project (http://osm2vectortiles.org/downloads/ ).

**Comment by sfkeller** [comment]
I think such raster tiles should file be loaded through the normal menu "Add Raster Layer..." (and GDAL).

**Comment by simgislab** [comment]
we're still working on it

**Comment by simgislab** [comment]
implemented
