### ISSUE TITLE
проблемы с установкой дополнительных подложек

### ISSUE THREAD

**Issue by lexusgol** [nextgis/quickmapservices#42]
![- -1](https://cloud.githubusercontent.com/assets/14974211/10275848/dc29d648-6b5b-11e5-82c3-11f668fde1d1.jpg)

Версия QGIS	2.8.3-Wien	Ревизия	eb1365a
Версия Qt при сборке	4.7.1	Текущая версия Qt	4.7.1
Версия GDAL/OGR при сборке	2.0.0dev	Текущая версия GDAL/OGR	2.0.0dev
Версия GEOS при сборке	3.4.2-CAPI-1.8.2	Текущая версия GEOS	3.4.2-CAPI-1.8.2 r3921
Версия PostgreSQL	8.3.10	Версия SpatiaLite	4.1.1
Версия QWT	5.2.1	Версия PROJ.4	480
Версия QScintilla2	2.6.2

nextgis qgis 15.4.88

**Comment by simgislab** [comment]
за прокси?

**Comment by BishopGIS** [comment]
Нет не за прокси. Это на нашем подключении к интернету.

**Comment by simgislab** [comment]
а что в нем особенного?

**Comment by simgislab** [comment]
дело не в нашем интернете, не работает и в других местах в Windows, в Ubuntu работает везде.

**Comment by simgislab** [comment]
работает в новой сборке NextGIS QGIS

переоткройте если это не так
