### ISSUE TITLE
При добавелнии плагина в виде кнопки на панели инструментов он пропадает из меню Интернет

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/quickmapservices#45]
У меня плагин пропал из меню интернет и доступен только в панели инструментов.
Это норма или баг?

**Comment by simgislab** [comment]
вот эта галка не включена ли?

![](http://m-d.me/img/ss/20151211-789-46kb.jpg)

У меня при включении - из меню QMS пропадает и если у тебя так же, то это баг.

**Comment by yellow-sky** [comment]
Это не баг. Там же ангельским по серому написано - переместить в панель и
меню Слои.
Если галка стоит, открываем меню Слой -> Добавить слой и видим QMS. Кнопка
же переезжает на панель со слоями.
Если не стоит - то в меню и на панели Интернет.

11 декабря 2015 г., 18:38 пользователь Maxim Dubinin <
notifications@github.com> написал:

> вот эта галка не включена ли?
>
>
> <https://camo.githubusercontent.com/24e74d33345c7a965ffbccc92cd46857789ce78c/687474703a2f2f6d2d642e6d652f696d672f73732f32303135313231312d3738392d34366b622e6a7067>
>
> У меня при включении - из меню QMS пропадает и если у тебя так же, то это
> баг.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/quickmapservices/issues/45#issuecomment-163966558>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by simgislab** [comment]
если в другое меню перемещается, то да, не баг, сорри

**Comment by BishopGIS** [comment]
А почему и там и там не сделать? А то как-то странно.

**Comment by yellow-sky** [comment]
Кнопочек и так девать некуда. Кто-то спрашивал - а зачем и в меню и на
панели?

2015-12-11 20:32 GMT+03:00 Dmitry Baryshnikov <notifications@github.com>:

> А почему и там и там не сделать? А то как-то странно.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/quickmapservices/issues/45#issuecomment-163998437>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by BishopGIS** [comment]
Мало ли кто что спрашивал. Есть правила хорошего тона. Кнопка - для мыши, меню, для клавы.

**Comment by simgislab** [comment]
Дима, в смысле и там и там? Сейчас оно и есть и там и там. 
Либо в меню Web и панели Интернет
Либо в меню Layer и панели Manage layers.

Что не так сейчас?

**Comment by BishopGIS** [comment]
Должно быть и там и там, а не либо либо. Ну это же элементарно - все кнопки панели инструментов должны иметь дубли в меню.

**Comment by simgislab** [comment]
отформатировал, ты не понял, мне кажется, еще раз, сейчас так:
Либо:
     в меню Web и панели Интернет
Либо:
     в меню Layer и панели Manage layers.

Т.е. все кнопки ИМЕЮТ дубли в меню.

**Comment by BishopGIS** [comment]
У меня ни в одном меню нету QuickMapServices, только на панели - это мне автор подсуропил. Чего-то там понажимал.

**Comment by BishopGIS** [comment]
Переустановка помогла.
