### ISSUE TITLE
Проблема с проекциями

### ISSUE THREAD

**Issue by pavelpromin** [nextgis/quickmapservices#5]
Если для слоя (пробовал только TMS) указана "своя" проекция (отличная от EPSG3857), то при проецировании на лету, когда используется EPSG3857, она не учитывается.

![423](https://cloud.githubusercontent.com/assets/532316/5787045/8fe7ac90-9e12-11e4-870b-5f1afe5be993.jpg)
здесь у подложки(используются тайлы яндекс.карт) проекция отличная от EPSG3857

**Comment by yellow-sky** [comment]
В данный момент проекции для тайловых слоев TMS провайдера не поддерживается. Указать её просто нет возможности. Для не сферического меркатора можно использовать GDAL драйвер.
Дублирует #4
