### ISSUE TITLE
Модуль не запускается если учётная запись пользователя содержит русские буквы

### ISSUE THREAD

**Issue by JogicPogic** [nextgis/quickmapservices#50]
Модуль не запускается если учётная запись пользователя содержит русские буквы.
Проверено на Windows 7 и QGIS 2.12.
![qgis](https://cloud.githubusercontent.com/assets/13277024/12016766/f4adec2a-ad70-11e5-9502-984674dade89.png)

**Comment by yellow-sky** [comment]
Duplicate #28
