### ISSUE TITLE
QGIS crashes pointing to libjpeg/jdapimin

### ISSUE THREAD

**Issue by ecodiv** [nextgis/quickmapservices#51]
I am running QGIS 2.12 (but same happened on QGIS master), compiled on Ubuntu 14.04. When enabling the Quickmapservices addon, QGIS crashes without any message.

Just in case it has to do with some warnings when starting up QGIS, I am copying those warning messages below:

```
$ qgis
Warning: loading of qgis translation failed [/usr/local/qgis/share/qgis/i18n//qgis_en_US]
Warning: loading of qt translation failed [/usr/share/qt4/translations/qt_en_US]
Warning: QCss::Parser - Failed to load file  "/style.qss" 
Warning: QVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const: Condition failed: action 
Warning: QVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const: Condition failed: action 
Warning: void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "&Toolbox" under id 264 
Segmentation fault (core dumped)
```

**Comment by spencerrecneps** [comment]
I've been having the same problem on Ubuntu 15.10 with QGIS 2.12 as recently as this weekend.

**Comment by simgislab** [comment]
All is ok for me on Ubuntu 14.04 and 2.14, not sure what we can do here.

**Comment by simgislab** [comment]
or from newest release

**Comment by ecodiv** [comment]
Tried it again today, with updated QGIS master on Ubuntu 14.04. Same problem, segmentation fault (core dumped). What would be the best way to test this further, check what is going wrong?

**Comment by ecodiv** [comment]
Not sure if this helps, but when running under dbg, the following was printed when attempting to open the plugin. Instead of crashing, QGIS freezes in this case.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff103313c in jpeg_CreateDecompress (cinfo=0x55c7e28, version=80, structsize=656)
    at libjpeg/jdapimin.c:37
37	    ERREXIT2(cinfo, JERR_BAD_LIB_VERSION, JPEG_LIB_VERSION, version);
(gdb)

**Comment by spencerrecneps** [comment]
Is there more information needed for this bug? I'm still experiencing issues on Ubuntu 16.04 and QGIS 2.16.

**Comment by ecodiv** [comment]
Just updated my QGIS to 2.18 (manually compiled on Ubuntu 16.04) and I am still experiencing this issue. Any clues where to look for the cause / solution?

**Comment by spencerrecneps** [comment]
I'm still experiencing this issue on a fresh install of 2.18 from source. I ran a debug session and saved a screenshot of the messages resulting in a segfault.
![image](https://cloud.githubusercontent.com/assets/4584258/22702648/03903562-ed27-11e6-8610-fa3f3a3cc25d.png)

It appears to be an issue with a bad call to libjpeg.

I also noticed that the problem only occured once I enabled the additional providers in the settings. Now that it's broken I can't go back into settings and test it again, but hopefully that offers a clue.

**Comment by ecodiv** [comment]
I am also still experiencing the same with a fresh install of 2.18 from source on Ubuntu 16.04, also with segfault.

**Comment by cubarro** [comment]
My version of QMS also crashed, but after addon is enabeled and downloaded tiles from OSM server.

When add OSM Standard. Counting from 1 to 20. In 20 is out of qgis. No error messages.
Using Linux Mint 18.1 64 bits, Qgis 2.14.12 and QMS 0.18.4.

I deleted all Qgis, grass, saga, scipy and depedencies with **purge**. Re-installed and crashed the same.

Another system with Linux Mint 18.1 32 bits, same 2 GB ram is running very well.  I used same steps for installing complete system.

What could I do?

**Comment by spencerrecneps** [comment]
@simgislab This bug has been open for a year now with no fix. Has this issue been forgotten?

**Comment by cubarro** [comment]
And is curious that is not present in my system with 32 bits.

**Comment by simgislab** [comment]
@cubarro, please don't cross-post, it doesn't help. You didn't provide any info linking your crash and this one.

@spencerrecneps there is not much we can do. It is not reproducible and from stacktrace above it seems like it is related to system libs/general QGIS.

Consider signing up for our support http://nextgis.com/pricing, than we'll be able to have a look in more detail.

**Comment by spencerrecneps** [comment]
@simgislab thanks for the response. For reference, I've filed a bug with QGIS:
http://hub.qgis.org/issues/16326

**Comment by spencerrecneps** [comment]
@simgislab The response from the QGIS team (in the bug report linked above) indicates that the problem lies with QMS, not with QGIS itself. Any thoughts?

I have a hunch that you're right about the bug being in QGIS itself but I'd need to be able to provide them more information. If you have any ideas for further testing or something please let me know. Thanks!

**Comment by simgislab** [comment]
lot's of changes since, please reopen if necessary with updated case
