### ISSUE TITLE
<type 'exception.Exception'> 6 error on getting contributed services

### ISSUE THREAD

**Issue by trolleway** [nextgis/quickmapservices#55]
При нажатии "получить дополнительные источнки данных" выдаётся ошибка.

Имя пользователя на английском. 
![default](https://cloud.githubusercontent.com/assets/4630662/12750296/40b3e3c8-c9c7-11e5-8164-fa8147b9d37e.jpg)

**Comment by yellow-sky** [comment]
Версия инсталятора NGQ какая?

2 февраля 2016 г., 16:09 пользователь Artem Svetlov <
notifications@github.com> написал:

> При нажатии "получить дополнительные источнки данных" выдаётся ошибка.
>
> Имя пользователя на английском.
> [image: default]
> <https://cloud.githubusercontent.com/assets/4630662/12750296/40b3e3c8-c9c7-11e5-8164-fa8147b9d37e.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/quickmapservices/issues/55>.
>



-- 

Best regards,

Nikulin Eugeny

**Comment by simgislab** [comment]
подтверждаю, могу дать доступ к компу
версия 110

**Comment by simgislab** [comment]
в 110 все ок
