### ISSUE TITLE
Ошибка при установке модуля

### ISSUE THREAD

**Issue by mfana-wabane** [nextgis/quickmapservices#56]
При попытке установить модуль происходит ошибка. 
Win10 x64. 
Лог:
Не удалось загрузить модуль quick_map_services из-за ошибки при вызове его метода initGui() 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 17: ordinal not in range(128) 
Traceback (most recent call last):
  File "D:/QGIS/apps/qgis/./python\qgis\utils.py", line 315, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/���� � ����/.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 112, in initGui
    self.build_menu_tree()
  File "C:/Users/���� � ����/.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 232, in build_menu_tree
    self.groups_list = DsGroupsList(self.locale, self.custom_translator)
  File "C:/Users/���� � ����/.qgis2/python/plugins\quick_map_services\ds_groups_list.py", line 46, in __init__
    self._fill_groups_list()
  File "C:/Users/���� � ����/.qgis2/python/plugins\quick_map_services\ds_groups_list.py", line 53, in _fill_groups_list
    self._read_ini_file(root, ini_file)
  File "C:/Users/���� � ����/.qgis2/python/plugins\quick_map_services\ds_groups_list.py", line 75, in _read_ini_file
    error_message = 'Group INI file can\'t be parsed: ' + e.message
  File "D:/QGIS/apps/qgis/./python\qgis\utils.py", line 58, in showWarning
    "warning:%s\ntraceback:%s" % (warnings.formatwarning(message, category, filename, lineno), stk),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 17: ordinal not in range(128)

Версия Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Версия: 2.12.3-Lyon Lyon, 99ac688 

Python Path:
D:/QGIS/apps/qgis/./python/plugins\processing
D:/QGIS/apps/qgis/./python
C:/Users/Жека и Таня/.qgis2/python
C:/Users/Жека и Таня/.qgis2/python/plugins
D:/QGIS/apps/qgis/./python/plugins
D:\QGIS\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
D:\QGIS\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
D:\QGIS\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
D:\QGIS\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
D:\QGIS\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
D:\QGIS\bin\python27.zip
D:\QGIS\apps\Python27\DLLs
D:\QGIS\apps\Python27\lib
D:\QGIS\apps\Python27\lib\plat-win
D:\QGIS\apps\Python27\lib\lib-tk
D:\QGIS\bin
D:\QGIS\apps\Python27
D:\QGIS\apps\Python27\lib\site-packages
D:\QGIS\apps\Python27\lib\site-packages\PIL
D:\QGIS\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
D:\QGIS\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
D:\QGIS\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
D:\QGIS\apps\Python27\lib\site-packages\win32
D:\QGIS\apps\Python27\lib\site-packages\win32\lib
D:\QGIS\apps\Python27\lib\site-packages\Pythonwin
D:\QGIS\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
D:\QGIS\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg
D:\QGIS\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
D:\QGIS\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
D:\QGIS\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Жека и Таня/.qgis2//python
D:\QGIS\apps\qgis\python\plugins\fTools\tools

**Comment by simgislab** [comment]
похоже у вас эта проблема: https://github.com/nextgis/quickmapservices/issues/50

Если не умеете собирать из кода, то скоро будет новый релиз QMS.

**Comment by mfana-wabane** [comment]
Ух-ух-ты :) От кроссплатформенного ПО такого не ожидаешь.
Но спасибо за наводку.

**Comment by simgislab** [comment]
причем тут кроссплатформенность, это баг и он исправлен
