### ISSUE TITLE
QGIS crashes when activating QuickMapServices

### ISSUE THREAD

**Issue by pcav** [nextgis/quickmapservices#57]
I get replicable crashes on QGIS 2.8.6 (Debian Sid) when activating a QMS layer, with OTF on a projection different from 3857. It was working until recently.

**Comment by simgislab** [comment]
can you try updating your QMS from the master here and see if it happens?

**Comment by pcav** [comment]
With the recent version just released the problem seems gone - Thanks Maxim!

**Comment by simgislab** [comment]
great, thanks!
