### ISSUE TITLE
Ошибки в заголовках окон

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/quickmapservices#59]
Должно быть "Выберите ..." или "Выбрать", но точно не "Выбирите..."

![qms error 2](https://cloud.githubusercontent.com/assets/6493848/13725205/a458a762-e8ab-11e5-8b6e-90a1affe9589.png)
![qms error 1](https://cloud.githubusercontent.com/assets/6493848/13725204/a45702a4-e8ab-11e5-8680-f2f2b271d2ac.png)

Так как в альтернативных формах - "Создать ресурс/группу", то лучше поменять на "Выбрать ...".

**Comment by simgislab** [comment]
Аня, https://github.com/nextgis/quickmapservices/blob/master/src/i18n/QuickMapServices_ru.ts

**Comment by Kinda-me** [comment]
[Fixed.](https://github.com/nextgis/quickmapservices/commit/a31a7120ea574f2173635ba4c8e4e223681febaf)
