### ISSUE TITLE
2gis не отключается через панель управления видимостью

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/quickmapservices#60]
![bug](https://cloud.githubusercontent.com/assets/6493848/13730255/676c8c6e-e95b-11e5-86b5-b5d81d7a5ba7.gif)

С остальными группами/сервисами все ок.

**Comment by alisovenko** [comment]
Какое значение имеет переменная реестра
HKEY_CURRENT_USER\SOFTWARE\NextGIS\QuickMapServices\hide_ds_id_list_str
1. до снятия галочки
2. после снятия галочки и сохранения настроек
?

**Comment by Kinda-me** [comment]
Проблема решилась перезагрузкой компьютера :)

**Comment by simgislab** [comment]
все равно странно же

**Comment by Kinda-me** [comment]
Да, но теперь не воспроизводится.
