### ISSUE TITLE
'QPyNullVariant' object has no attribute 'split' - OSX 10.11, QGIS 2.14

### ISSUE THREAD

**Issue by romainbh** [nextgis/quickmapservices#62]
I'm using QGIS 2.14 on OSX 10.11. When I install QMS, I get this error message:

```
Impossible de charger l'extension quick_map_services provoque une erreur lors de l'appel de sa méthode initGui() {Could not load extension quick_map_services causes an error when calling its method initGui()}

AttributeError: 'QPyNullVariant' object has no attribute 'split' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 315, in startPlugin
    plugins[packageName].initGui()
  File "/Users/username/.qgis2/python/plugins/quick_map_services/quick_map_services.py", line 117, in initGui
    self.build_menu_tree()
  File "/Users/username/.qgis2/python/plugins/quick_map_services/quick_map_services.py", line 241, in build_menu_tree
    ds_hide_list = PluginSettings.get_hide_ds_id_list()
  File "/Users/username/.qgis2/python/plugins/quick_map_services/plugin_settings.py", line 85, in get_hide_ds_id_list
    return cls.get_settings().value('hide_ds_id_list_str', "").split(";")
AttributeError: 'QPyNullVariant' object has no attribute 'split'


Version de Python : 2.7.10 (default, Oct 23 2015, 18:05:06) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] 
Version de QGIS : 2.14.0-Essen Essen, exported 

Chemin Python :
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/username/.qgis2/python
/Users/username/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Library/Python/2.7/site-packages
/Users/username/.qgis2//python
/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools
```

**Comment by simgislab** [comment]
seems like this is related to the fact that you're on MacOS, we never tested on it

**Comment by romainbh** [comment]
Yes I think so too because I use QSM on Ubuntu 15.10 and Windows 7/10 without any problem with the same version of QGIS (2.14).
Thanks a lot for this so cool plugin ;)

**Comment by gmorain** [comment]
Hi, 

I had it working on OS X before, but it seems yesterday's 10.11.4 OS X update broke the plugin. I have the same error message as romainbh when starting QGIS after QSM installation : 
AttributeError: 'QPyNullVariant' object has no attribute 'split'

**Comment by gmorain** [comment]
OK, got it working again by switching back to QSM 0.15 on both machines

the dirty way I followed to downgrade the plugin :
- have the last version 'installed' using QGIS plugin manager
- quit QGIS
- open a shell window
$ cd ~/.qgis2/python/plugins
$ git clone https://github.com/nextgis/quickmapservices.git
$ cd quickmapservices/
$ git checkout 2a6a31b
$ open ./src
$ open ../quick_map_services/
- the two last commands will open Finder windows
- delete everything from quick_map_services/
- copy everything from src/ to quick_map_services/
- start QGIS

Et voilà !

I guess when looking at the changelog and the error message ("ds_hide_list = PluginSettings.get_hide_ds_id_list()"), the culprit may be the show/hide feature.

0.16:
* Convenient forms for adding, editing, removing services or groups
* It is now possible to hide and show services/groups to shorten the list
* Fixed plugin start if user name has non-ASCII symbols

**Comment by simgislab** [comment]
yes,

```cls.get_settings().value('hide_ds_id_list_str', "").split(";")```

this tries to save a list of basemaps to settings, but for some reason not working under OSX

**Comment by yellow-sky** [comment]
@gmorain  Please, try last version from repository

**Comment by gmorain** [comment]
Hi @yellow-sky, 

I had some errors when playing with the manual procedure I used yesterday. 0.15 tag works, but I get some other errors when checking out later commits. Since the change is limited to one line, this is what worked:
- I removed all traces of the plugins in the QGIS plugins folder
- I reinstalled the 0.16 release using QGIS plugin manager
- I got the error at the start of this issue
- I closed QGIS
- I manually changed line 85 of plugin_settings.py as done in commit fe2333456b6e94afcc94d6bf3f79d5cf85eba1c6
- I started QGIS

=> success !

I even tried successfully to hide some layers using the settings panel.
I guess you can push the new release to the QGIS repo, I will reinstall from here as soon as you have done it so I can confirm it works end to end

**Comment by gmorain** [comment]
@yellow-sky, 

I had the same issue as #63 reported a few minutes ago when updating through the plugin manager, but removing / installing the plugin using QGIS plugin manager fixed it.

BTW, it is the error message I had earlier when playing with the git version, but since checking out tag 0.16 gave me this error even though 0.16 from the QGIS repo did not, I though is was more linked to my manual procedure to install the plugin.

**Comment by simgislab** [comment]
tested also on Win and Linux (Ubuntu), visibility management seems to work fine now

please use version from official repo

**Comment by gmorain** [comment]
Indeed, I think the update gave me 0.16.1 whereas the subsequent delete / install gave 0.16.2 ;-)

Thanks for fixing the issue !

**Comment by romainbh** [comment]
Tested today on OSX and all is OK! Thanks a lot!
