### ISSUE TITLE
Last update (23/03) brokes the plugin uploading

### ISSUE THREAD

**Issue by ghtmtt** [nextgis/quickmapservices#63]
Hi,
after the plugin update it seems impossible to load it (not valid).
This the error:
```
ImportError 
No module named resources_rc
```

Thanks

**Comment by gmorain** [comment]
Hi @ghtmtt,

Had the same issue when updating from 0.16, but removing / reinstalling the plugin worked fine.

**Comment by ghtmtt** [comment]
@gmorain 
doesn't work for me...

**Comment by simgislab** [comment]
our bad, try updating to 0.16.2 please

**Comment by ghtmtt** [comment]
yep! fine! thanks for the fix

**Comment by gmorain** [comment]
@ghtmtt 
The release I got when updating was 0.16.1, but on reinstalling I got 0.16.2 (did not notice that earlier) so what made it work on my machine was the timing of the 0.16.2 release ;-)

**Comment by simgislab** [comment]
0.16.1 was our packaging mistake, 0.16.2 fixed that

thanks for reporting
