### ISSUE TITLE
Does not save "Y Origin top"

### ISSUE THREAD

**Issue by zimirrr** [nextgis/quickmapservices#64]
When creating new TMS, checkbox "**Y Origin top**" doesn't save "**checked**"
For example I wanted to add this service 
http://tms0.visicom.ua/2.0.0/planet3/base_en/{z}/{x}/{y}.png
![error](https://cloud.githubusercontent.com/assets/1256802/14113706/c9028e3c-f5dc-11e5-84cb-f5c24ee96d01.png)

**Comment by simgislab** [comment]
confirmed

**Comment by simgislab** [comment]
fixed with https://github.com/nextgis/quickmapservices/commit/c29cd2e304462536e0859d807673ac69acf90da4

**Comment by zimirrr** [comment]
Now it saves, but tiles doesn't work correctly.

**Comment by simgislab** [comment]
apparently this is not enough:

1. Save a project with this layer
2. Try to reopen it:

>ValueError: invalid literal for int() with base 10: 'true' 
>Traceback (most recent call last):
>  File "/home/sim/.qgis2/python/plugins/quick_map_services/py_tiled_layer/tilelayer.py", line 587, in readXml
>    self.layerDef.yOriginTop = int(self.customProperty("yOriginTop", 1))
>ValueError: invalid literal for int() with base 10: 'true'

**Comment by drnextgis** [comment]
Closed via https://github.com/nextgis/quickmapservices/commit/23e752b1190cacc15c8eb8980f09fc730e436efb
