### ISSUE TITLE
Add WFS services support

### ISSUE THREAD

**Issue by simgislab** [nextgis/quickmapservices#65]

**Comment by sfkeller** [comment]
WFS is supported by QGIS core: Why would we want this in this plugin too?

BTW: If it's about supporting ArcGIS Feature Services via "ArcGIS REST API" try "ArcGIS REST API Connector: http://plugins.qgis.org/plugins/connector/ .

**Comment by simgislab** [comment]
we'd like QMS to be library of services independent from QGIS

**Comment by sfkeller** [comment]
Do I undersand it correctly, that you now already have implemented WFS in QMS? If yes, which OGC WFS version?

Though I asked about why WFS, it's interesting to see this implemented! In this case it's easier to implement e.g. authorization (see #80 and #81 ).

**Comment by sfkeller** [comment]
Can you give an example of a valid WFS configuration (URL)? When I go to Settings and add an own service of type WFS (like this URL http://demo.opengeo.org/geoserver/wfs ) I can save this user config. but when I select it, no layer is being added to the QGIS project. => Should the WFS URL contain a layer parameter?
