### ISSUE TITLE
Does not work "Y Origin top" 

### ISSUE THREAD

**Issue by zimirrr** [nextgis/quickmapservices#66]
_I couldn't reopen previous issue, so creating new._
After previous fix it saves checkbox value. But it doesn't work.

For example I wanted to add this service again 
http://tms0.visicom.ua/2.0.0/planet3/base_en/{z}/{x}/{y}.png
![error](https://cloud.githubusercontent.com/assets/1256802/14113706/c9028e3c-f5dc-11e5-84cb-f5c24ee96d01.png)

**Comment by simgislab** [comment]
does it work somewhere else?

**Comment by drnextgis** [comment]
Works as expected here. `Y Origin top` should be unchecked.

**Comment by zimirrr** [comment]
Yep.. my fault. Everything fine now.
