### ISSUE TITLE
Offer default icon when adding a service in Settings

### ISSUE THREAD

**Issue by sfkeller** [nextgis/quickmapservices#70]
When adding a new service (in menu Settings) it's currently mandatory to add an Icon to the service. 
But services often don't offer icons and users don't have own ones.
So, it would be convenient to make this icon value optional and setup a default one.
One could also leave it mandatory but deliver a default icon file in the plugin directory.

**Comment by simgislab** [comment]
@yellow-sky I wan irritated by this as well

How about making optional and use placeholder icon if no icon is set?
