### ISSUE TITLE
Grayscale checkbox missing

### ISSUE THREAD

**Issue by simgislab** [nextgis/quickmapservices#73]
QGIS 2.14.1
QMS 0.16.2
64 bit install running on windows 10

![](http://m-d.me/img/ss/20160422-a6p-200kb.jpg)

Reported by Mike Ederer

**Comment by simgislab** [comment]
I can't confim it neither on the same version of QGIS under Ubuntu, not on 2.15dev installed via OSGeo4W on Win7

**Comment by yellow-sky** [comment]
![image](https://cloud.githubusercontent.com/assets/1277422/14755117/852d7c48-08e8-11e6-9c57-2bee61de0809.png)

**Comment by yellow-sky** [comment]
Try to reinstall the plugin

**Comment by simgislab** [comment]
>I tried reinstalling several different times, several different ways. Rebooting, cleaning system temp files etc. Nothing worked. I decided to start playing around with disabling other plugins… that’s where it got interesting. I believe there is a conflict with your plugin and “go2streetview”. Weird things were happening when I was playing around with turning that one on and off. It might be connected to “google maps connection engine” as well. Both were enabled when I did not have grayscale mode. Sometimes I was getting python read error message referring to “go2streetview”. Other times the properties box for your plugin would not even appear on screen. Anyway, with the right combination of turning on and off that plugin in conjunction with your plugin. Saving map and exiting, then reopening I have the grayscale mode available as long as “go2streetview” is turned off... I think.  It seems like your plugin is stable and not getting python errors after exiting QGIS and reopening multiple times. Not sure of the proper order, if one is even required, of doing things though….sorry.

**Comment by Komzpa** [comment]
Reproducible with 0.18.6 and this QGIS:
![image](https://user-images.githubusercontent.com/810638/27385976-0378895a-569d-11e7-87ee-8ca05637634f.png)

**Comment by Komzpa** [comment]
Update to 0.18.7 repaired it without QGIS restart.

**Comment by simgislab** [comment]
I'm glad it works)
