### ISSUE TITLE
Plugin fails to start if requests and PIL are not present on system

### ISSUE THREAD

**Issue by magerlin** [nextgis/quickmapservices#76]
Latest update of today in win 64 bit, Qgis 2.14.2:
![image](https://cloud.githubusercontent.com/assets/1887531/15568035/169cfe0a-232a-11e6-827c-5a9e3323e910.png)

**Comment by JesusLopTem** [comment]
Same problem on Mac 10.9.5, Qgis 2.14.2

**Comment by EdwardHyvernat** [comment]
Same problem, same message, on win 64 bits, QGIS 2.14.3

**Comment by alexbnmr** [comment]
Idem on Win32 QGis 2.14.3 when installing :

Impossible de charger l'extension quick_map_services provoque une erreur lors de l'appel de sa méthode classFactory() 

ImportError: No module named requests 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 306, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/AB/.qgis2/python/plugins\quick_map_services\__init__.py", line 34, in classFactory
    from .quick_map_services import QuickMapServices
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/AB/.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 39, in 
    from qms_service_toolbox import QmsServiceToolbox
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/AB/.qgis2/python/plugins\quick_map_services\qms_service_toolbox.py", line 10, in 
    from .qms_external_api_python.client import Client
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/AB/.qgis2/python/plugins\quick_map_services\qms_external_api_python\client.py", line 1, in 
    from api.api_v1 import ApiClientV1 as Client
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/AB/.qgis2/python/plugins\quick_map_services\qms_external_api_python\api\api_v1.py", line 3, in 
    from .api_abstract import ApiClient
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/AB/.qgis2/python/plugins\quick_map_services\qms_external_api_python\api\api_abstract.py", line 1, in 
    from requests import get
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named requests


Version de Python : 2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)] 
Version de QGIS : 2.14.3-Essen Essen, cf2ebb8 

Chemin Python :
C:/Users/AB/.qgis2/python/plugins\processing_prepair
C:/Users/AB/.qgis2/python/plugins\processing_circuitscape
C:/Users/AB/.qgis2/python/plugins\processing
C:/PROGRA~1/QGISES~1/apps/qgis/./python
C:/Users/AB/.qgis2/python
C:/Users/AB/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1\bin\python27.zip
C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1\apps\Python27\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1\bin
C:\PROGRA~1\QGISES~1\apps\Python27
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:/Users/AB/.qgis2//python
C:\Users\AB\.qgis2\python\plugins\cadastre/forms
C:\Users\AB\.qgis2\python\plugins\DigitizingTools\tools
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:\Users\AB\.qgis2\python\plugins\SelectTools/tools
C:/Users/AB/.qgis2/python/plugins\shpsync\xlrd-0.9.4-py2.7.egg
C:/Users/AB/.qgis2/python/plugins\shpsync\xlwt-1.0.0-py2.7.egg
C:/Users/AB/.qgis2/python/plugins\shpsync\xlrd-0.9.4-py2.7.egg
C:/Users/AB/.qgis2/python/plugins\shpsync\xlwt-1.0.0-py2.7.egg
C:/Users/AB/.qgis2/python/plugins\shpsync\xlrd-0.9.4-py2.7.egg
C:/Users/AB/.qgis2/python/plugins\shpsync\xlwt-1.0.0-py2.7.egg

**Comment by Solski** [comment]
Same problem on Windows 10 32 bits, QGIS 2.14.2

**Comment by simgislab** [comment]
thanks for letting us know, we located the problem and fix will be there soon

**Comment by yellow-sky** [comment]
Please? try to update

**Comment by Solski** [comment]
Version 0.17.2 - problem solved

**Comment by JesusLopTem** [comment]
The problem here remains (Mac 10.9.5, Qgis 2.14.2). The plugin is broken: No module named PIL.

**Comment by spatialhast** [comment]
The same error 'No module named PIL' in Mac 10.10.5, QGIS 2.10.1-Pisa
Log:

```
Не удалось загрузить модуль quick_map_services из-за ошибки при вызове его метода classFactory()
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/user/.qgis2/python/plugins/quick_map_services/__init__.py", line 34, in classFactory
    from .quick_map_services import QuickMapServices
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/user/.qgis2/python/plugins/quick_map_services/quick_map_services.py", line 39, in 
    from qms_service_toolbox import QmsServiceToolbox
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/user/.qgis2/python/plugins/quick_map_services/qms_service_toolbox.py", line 10, in 
    from .qms_external_api_python.client import Client
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/user/.qgis2/python/plugins/quick_map_services/qms_external_api_python/client.py", line 1, in 
    from api.api_v1 import ApiClientV1 as Client
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/user/.qgis2/python/plugins/quick_map_services/qms_external_api_python/api/api_v1.py", line 4, in 
    from PIL import Image
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named PIL
Версия Python:
2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
Версия:
2.10.1-Pisa Pisa, 
Путь поиска Python: ['/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/user/.qgis2/python', u'/Users/user/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7', '/Library/Python/2.7/site-packages/numpy-override', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg', '/Applications/QGIS.app/Contents/MacOS/grass/etc/python', '/', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', u'/Users/user/.qgis2//python']

```

**Comment by simgislab** [comment]
PIL is missing in the system on Mac OS, we'll fix that

**Comment by JesusLopTem** [comment]
We can always install a previous version manually until the bug be solved.

**Comment by Tele-Pet** [comment]
Great idea @JesusLopTem.  Do you have a link to a previous version handy?  I'm not sure where to find that.

**Comment by JesusLopTem** [comment]
Sure, you can download it from here. [<http://plugins.qgis.org/plugins/quick_map_services/>](url)

**Comment by Tele-Pet** [comment]
Thanks @JesusLopTem.  Reverting to version [0.16.2](http://plugins.qgis.org/plugins/quick_map_services/version/0.16.2/) got it working again for me.

**Comment by yellow-sky** [comment]
request to all. please, update version and try to use

**Comment by JesusLopTem** [comment]
All ok now with Version 0.17.3. Thanks!

**Comment by simgislab** [comment]
Win 7, 32 bit, all fine

**Comment by magerlin** [comment]
Win 7, 64 bit ok too!

**Comment by simgislab** [comment]
looks like no more problems on this front

reopen if necessary
