### ISSUE TITLE
Version  0.17.2 Update won't install on Mac

### ISSUE THREAD

**Issue by CindyFowler** [nextgis/quickmapservices#82]
ERROR MESSAGE: This plugin is broken. No module named PIL
OPERATING SYSTEM: Mac  OS X 10.11.5El Capitan
QGIS INFO: 

 QGIS version
- 2.14.0-Essen
- QGIS code revision
- exported
- Compiled against Qt
- 4.8.6
- Running against Qt
- 4.8.6
- Compiled against GDAL/OGR
- 1.11.4
- Running against GDAL/OGR
- 1.11.4
- Compiled against GEOS
- 3.5.0-CAPI-1.9.0
- Running against GEOS
- 3.5.0-CAPI-1.9.0 r0
- PostgreSQL Client Version
- 9.4.4
- SpatiaLite Version
- 4.3.0a
- QWT Version
- 6.0.2
- PROJ.4 Version
- 492
- QScintilla2 Version
- 2.9.1

Thank you very much for your Plugin.  It works great and I use it everyday.  I just had a problem on the update.

**Comment by simgislab** [comment]
duplicate #76
