### ISSUE TITLE
All layers are labeled "MapQuest OSM" in layers panel

### ISSUE THREAD

**Issue by magerlin** [nextgis/quickmapservices#83]
Here I chose to add Stamen Water Color, but name is wrong:
![image](https://cloud.githubusercontent.com/assets/1887531/15710653/434aba42-280b-11e6-85e5-fd7b7ba7f55e.png)

QGIS 2.14.3, Win 7, 64 bit

Note: I does not always happen, right now I am not able to repeat it....

**Comment by yellow-sky** [comment]
version of QMS?

**Comment by magerlin** [comment]
0.17.3

**Comment by magerlin** [comment]
This is still happening in Qgis 2.16.3 and QuickMapServices v 0.17.8 - trying to add Mapsurfer Grayscale (in this example) names the layer something else:
![layer name](https://cloud.githubusercontent.com/assets/1887531/19116674/9c5dbbe8-8b16-11e6-9ef7-441876b0ea07.png).

And the code in the .qgs file is:

`   <layer-tree-layer expanded="1" checked="Qt::Checked" id="MapSurfer_OSM_Roads_Grayscale20161005155419289" name="Google Satellite">`

It appears that the given name is a name recently used for something else - perhaps your code does unintentionally reuse existing variable values - it does not reset it?

**Comment by simgislab** [comment]
also note missing grayscale option #95

**Comment by drnextgis** [comment]
Cannot reproduce bug here. @magerlin it looks like all works as expected?

**Comment by magerlin** [comment]
I cannot add anything to what I wrote on October 5th. 
It does not always happen to me either - but I cannot point out what makes it happen :-(

**Comment by simgislab** [comment]
@magerlin you're using latest QMS, right?

**Comment by magerlin** [comment]
Yes I use version 0.17.8

**Comment by simgislab** [comment]
we're nearing next release of QMS. Will it be possible for our dev to have a look at it at your machine (via teamviewer)? If yes, please write me at maxim.dubinin@nextgis.com and let me know when it can be done.
