### ISSUE TITLE
Use parameters and layers fields while adding WFS (same behavior as with adding WMS)

### ISSUE THREAD

**Issue by sfkeller** [nextgis/quickmapservices#84]
Referring to #65 can you give an example of a valid WFS service configuration, e.g. showing up in the nice QMS "Services panel"? 

When I go to QMS "Settings" and add an own service of type WFS (like this http://demo.opengeo.org/geoserver/wfs ) I can save this user config. But when I select it, no layer is being added to the QGIS project. What could be wrong?

**Comment by sfkeller** [comment]
I also can't see anything in the QGIS / Python logs... Here's another WFS to test this potentially nice feature: http://maps.zh.ch/wfs/TbaBaustellenZHWFS

**Comment by simgislab** [comment]
adding WFS service should allow stating what layer you need. And currently it doesn't. Looks like a bug.

@alisovenko can you please have a look?

**Comment by simgislab** [comment]
Ok, Figured it out. Everything is ok, it's just that current support for WFS services unlike WMS doesn't allow to layers and params separately and wants all of them passed in the url.

Working example: http://maxim.nextgis.com/api/resource/117/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=build&SRSNAME=EPSG:3857

I'm renaming the issue and reclassifying it as enhancement request. We definitely want the same behavior for WFS as for WMS.

**Comment by simgislab** [comment]
implemented

@sfkeller you can try adding your WFS services here: http://qms.nextgis.com
