### ISSUE TITLE
Set and use API key for services

### ISSUE THREAD

**Issue by hammad-tfg** [nextgis/quickmapservices#93]
Hi,

As MapQuest have discontinued direct tile access and only people with developer account (and key) will be able to access the tiles. http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

I was wondering if you will be able to deploy a new version of this plugin which enables users to input their developer key to use MapQuest tiles ?

Awaiting your response.

**Comment by simgislab** [comment]
Hi, that's good feature to have, but I can't put a date on when it arrives. Sponsoring it would help.

**Comment by hammad-tfg** [comment]
Hi @simgislab,

I just checked on MapQuest end as well. They have completely deprecated the tile service and in replacement has introduced a Static Map API which works with developer key. (15k requests / mo for free).

The Static API interface / contract / structure is completely different, lot of people complaining why MapQuest did that as it requires change of code / implementation everywhere it was being used. ([one example thread on MapQuest forum](https://developer.mapquest.com/forum/direct-tile-access-keys))

So i think it wont be just adding a query string containing developer key, like i had thought initially, but more work would be required.
