### ISSUE TITLE
Where is the option to change basemaps to Grayscale in QMS plugin for QGIS 2.16?

### ISSUE THREAD

**Issue by dionng** [nextgis/quickmapservices#95]
Has this feature been moved or removed?

**Comment by simgislab** [comment]
double click a basemap in layers list

![](http://m-d.me/img/ss/20160219-160212.png)

**Comment by dionng** [comment]
Sorry I should have made my question clearer.  The latest QuickMapServices plugin for QGIS v2.16 doesnt seem to have the Grayscale option anymore.

![image](https://cloud.githubusercontent.com/assets/5027701/16950925/2f98658e-4df5-11e6-8bff-4f7cc104445b.png)

**Comment by simgislab** [comment]
@dionng can you confirm it using latest QMS?

**Comment by simgislab** [comment]
closing due to lack of feedback, please reopen if issue persists
