### ISSUE TITLE
Mapbox services not working

### ISSUE THREAD

**Issue by cartochris** [nextgis/quickmapservices#96]
Hi

The Mapbox services (Gray and Satellite) both do not seem to load up, I receive a warning 'Failed to download all **\* files'.

Are there known issues with these services?

**Comment by spatialhast** [comment]
https://github.com/nextgis/quickmapservices_contrib/pull/39

**Comment by simgislab** [comment]
are you sure it's a good idea? The owner of those tokens might get charged if there is a lot of use. If understand correctly how this works.

**Comment by spatialhast** [comment]
for this 'pk.eyJ1IjoibWFwYm94IiwiYSI6IlhHVkZmaW8ifQ.hAMX5hSW-QnTeRCMAy9A8Q' token long time map tiles not available (possible owner delete this key). In my Mapbox profile I created new token ('pk.eyJ1IjoiaGFzdCIsImEiOiJjaXg1MG50NTQwMDFsMnpwYmJ4dDNkazBwIn0.Qc6IBm3O-I9zPDAgxrtxug') - you can use it.

**Comment by simgislab** [comment]
I understood this part.

Your account (even if you're on free plan) will be CHARGED if there will be enough tiles served from your token.

**Comment by simgislab** [comment]
this can't be fixed as we don't control services
reopen/contribute in https://github.com/nextgis/quickmapservices_contrib
or contribute/report at qms.nextgis.com
